### ISSUE TITLE
Labels get mixed up

### ISSUE THREAD

**Issue by xocasdashdash** [martin-helmich/prometheus-nginxlog-exporter#10]
So i have a bunch of different nginx locations, each writes to it's own file, the problem is that the labels applied to the metrics are getting mixed. 

This is the config file i have:

listen {
  port = 4040
}

namespace "pixel_server_pull_sync" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.pull_sync.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "pull_sync"
  }
}
namespace "pixel_server_ul_cb" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.ul_cb.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "ul_cb"
  }
}
namespace "pixel_server_bk_data" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.bk_data.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "bk_data"
  }
}
namespace "pixel_server_bk_data_mobile" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.bk_data_mobile.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "bk_data_mobile"
  }
}
namespace "pixel_server_br_sync" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.br_sync.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "br_sync"
  }
}
namespace "pixel_server_id_sync" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.id_sync.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "id_sync"
  }
}
namespace "pixel_server_pixel_brighttag" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.pixel_brighttag.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "pixel_brighttag"
  }
}
namespace "pixel_server_root" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.root.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "root"
  }
}
namespace "pixel_server_application" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $bytes_received $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $upstream_response_time $request_time"
  source_files = [
    "/var/log/nginx/prometheus.application.log"
  ]
  labels {
    app = "pixel_server"
    environment = "production"
    location= "application"
  }

And the metrics I'm seeing are for example this:
pixel_server_id_sync_http_response_count_total{app="production",environment="id_sync",location="pixel_server",method="GET",status="200"} 30355
pixel_server_id_sync_http_response_count_total{app="production",environment="id_sync",location="pixel_server",method="GET",status="304"} 2845

As you can see the app, environment and location labels are getting mixed. My suspicion is that on this lines https://github.com/martin-helmich/prometheus-nginxlog-exporter/blob/master/main.go#L149-L155

The configuration is not being read correctly

**Comment by martin-helmich** [comment]
:+1: Thanks for the report. I'll look into this as soon as I can find the time.

**Comment by martin-helmich** [comment]
@xocasdashdash OK, this was a really stupid beginner's mistake on my part, now fixed in #12. I've also published a [new release 1.0.1](https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/tag/v1.0.1). Would you mind giving it a test and checking if this issue still occurs?

**Comment by xocasdashdash** [comment]
@martin-helmich I don't think i'm gonna be able to do so, I ended up circumventing it limiting the number of labels per namespace to one. I saw the failing test and if it works there it should work correctly on my prod setup
