### ISSUE TITLE
Missing metrics when everything seems to be allright.

### ISSUE THREAD

**Issue by adambisek** [martin-helmich/prometheus-nginxlog-exporter#101]
Hello Martin,
I am running your exporter in Docker.

I have nginx logs (in volume) like this:
```
172.26.0.1 - - [25/Feb/2020:15:59:58 +0000] "GET / HTTP/1.1" 200 139362 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
172.26.0.1 - - [25/Feb/2020:15:59:58 +0000] "GET /static/js/bundle.44e2399c.js HTTP/1.1" 304 0 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
...
```

My config.hcl
```
listen {
  port = 4040
  address = "0.0.0.0"
}

consul {
  enable = false
  address = "localhost:8500"
  datacenter = "dc1"
  scheme = "http"
  token = ""
  service {
    id = "nginx-exporter"
    name = "nginx-exporter"
    tags = ["foo", "bar"]
  }
}

namespace "app1" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
  source {
    files = [
      "/var/log/nginx/access-exporter.log"
    ]
  }
  labels {
    app = "application-one"
    environment = "production"
    foo = "bar"
  }

  histogram_buckets = [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
}
```

I am 100% sure, that logs are mounted as a volume in `prometheus-nginxlog-exporter` (within docker-compose).
When I run container, I can see:

```
nginx-exporter_1  | loading configuration file /etc/prometheus-nginxlog-exporter.hcl
nginx-exporter_1  | using configuration {{%!s(int=4040) 0.0.0.0} {%!s(bool=false) localhost:8500 dc1 http  {nginx-exporter nginx-exporter [foo bar]}} [{app1 [] $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" map[foo:bar app:application-one environment:production] [] [] []}] %!s(bool=false)}
nginx-exporter_1  | starting listener for namespace app1
nginx-exporter_1  | running HTTP server on address 0.0.0.0:4040
```

On /metrics page I can't see any metrics.
I can see only: https://gist.github.com/adambisek/44b99ae75418566f92bd12a7474d364d

Could anyone help me find out why please?

**Comment by adambisek** [comment]
Figured it out.

Source files must be defined like this:

```
source_files = ["/var/log/nginx/access-exporter.log"]
```

NOT 

```
source {
   files []
}
```

Please update the docs.

**Comment by smazurov** [comment]
this tripped me up for a few hours, thanks @adambisek and please update the docs!

**Comment by martin-helmich** [comment]
@smazurov @adambisek Which version of the exporter are you using? As of 1.4.0, both syntaxes should be supported (with `source_files` having been there first, then being generalized to `source { files [...]}` to support different source types). If the latter does not work, this is NOT a documentation quirk, but an actual bug.

**Comment by smazurov** [comment]
whatever is `latest` in docker registry

**Comment by martin-helmich** [comment]
Stupid me 😞  -- `latest` still points to `v1.2.0` and seems to not have updated for some reason; I've manually moved the pointer to the *actual* latest version for now and will investigate as to why it didn't update automatically.

Sorry for the confusion!

**Comment by adambisek** [comment]
@smazurov For me it was couple of hours for three days :D

@martin-helmich Thanks. So I assume that latest is still backwards compatible and I don't need to change anything.
