### ISSUE TITLE
Cant make namespace with "-"

### ISSUE THREAD

**Issue by eskornev** [martin-helmich/prometheus-nginxlog-exporter#11]
Hello!
I'v got this error while setting my namespace "app2-eee":
panic: descriptor Desc{fqName: "app2-eee_http_response_count_total", help: "Amount of processed HTTP requests", constLabels: {}, variableLabels: [method status app environment]} is invalid: "app2-eee_http_response_count_total" is not a valid metric name

is there any method to get desired settings?

**Comment by martin-helmich** [comment]
The "namespace" is used as a prefix for the Prometheus metric names. These need to match the regular expression `^[a-zA-Z_:][a-zA-Z0-9_:]*$` (compare https://github.com/prometheus/common/blob/ad540c5ab198ab0c5172f5c6b602a49ab911b5ef/model/metric.go#L25-L28), which is enforced by the Prometheus client library. For this reason, there is no way to have a namespace containing a dash (or any other character not matched by this regexp).
