### ISSUE TITLE
Error `illegal seek` tailing access.log file

### ISSUE THREAD

**Issue by GrzegorzKaczan** [martin-helmich/prometheus-nginxlog-exporter#113]
**Issue type**:
> Bug report  

**What happened**:
Running exporter along nginx inside a container, run by supervisor.
Starting exporter to listen on nginx access.log i get:
```
running HTTP server on address 0.0.0.0:8082
2020/04/30 10:51:56 Seeked /var/log/nginx/access.log - &{Offset:0 Whence:2}
panic: Seek error on /var/log/nginx/access.log: seek /var/log/nginx/access.log: illegal seek

goroutine 42 [running]:
main.processNamespace.func1(0xa0d220, 0xc000064290)
        /home/runner/work/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter/main.go:260 +0x3e
github.com/martin-helmich/prometheus-nginxlog-exporter/tail.(*followerImpl).OnError.func1(0xc0001286a0, 0x987e38)
        /home/runner/work/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter/tail/tailer.go:60 +0x61
created by github.com/martin-helmich/prometheus-nginxlog-exporter/tail.(*followerImpl).OnError
        /home/runner/work/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter/tail/tailer.go:57 +0x49

```

**What you expected to happen**:
Exporter runs and listens on the log successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Having Dockerfile such as:
```
FROM hoosin/alpine-nginx-nodejs:latest
RUN apk add nginx-mod-http-headers-more
RUN apk add supervisor
COPY src/main/docker/supervisord.conf /etc/
ENV NGINX_CONF /etc/nginx/
RUN touch /var/run/nginx.pid

RUN touch /var/run/nginx.pid && \
  chown -R nginx:nginx /var/run/nginx.pid && \
  chown -R nginx:nginx /var/cache/nginx

WORKDIR /usr/src/app

COPY src/main/nginx/prometheus-nginxlog-exporter prometheus-nginxlog-exporter
COPY src/main/nginx/nginx.conf /etc/nginx/nginx.conf
COPY src/main/nginx/nginx.site.conf /etc/nginx/sites-enabled/nginx.site.conf
RUN nginx -t

ENTRYPOINT /usr/bin/supervisord -c /etc/supervisord.conf
```

and Supervisor with disabled log rotation:
```
[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
childlogdir=/tmp
pidfile = /tmp/supervisord.pid

[program:nginx]
command=nginx
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0

[program:nginx_prometheus_exporter]
command=/usr/src/app/prometheus-nginxlog-exporter  -listen-port=8082 /var/log/nginx/access.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=3
```

**Environment**:
- Exporter version: 1.5.1
- OS (e.g. from /etc/os-release): Alpine
- Others: Docker

**Comment by martin-helmich** [comment]
Any chance that `/var/log/nginx/access.log` is not a regular file, but something else? A named pipe, perhaps? Or a symlink to `/dev/stdout`?

**Comment by GrzegorzKaczan** [comment]
Hey,

Yeah its a symlink to `/dev/stdout`. But i removed that from supervisor config too and it seems to be setup anyway, i guess by docker itself to intercept logs?

```
-> % docker exec f7467df6dd5b stat /var/log/nginx/access.log
  File: '/var/log/nginx/access.log' -> '/dev/stdout'
  Size: 11        	Blocks: 0          IO Block: 4096   symbolic link
Device: 6ch/108d	Inode: 41812122    Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (  100/   nginx)   Gid: (  101/   nginx)
Access: 2018-12-21 01:18:39.000000000
Modify: 2018-12-21 01:18:39.000000000
Change: 2020-04-30 11:15:17.000000000

```

**Comment by martin-helmich** [comment]
I'm not familiar with the base image, but I suspect that the symlink is simply baked into the image; it allows you to view the access logs using the `docker logs` command.

In this case, I would suggest one of the following options:

- If you can live without having the access logs in `docker logs`, simply remove the symlink to `/dev/stdout` (presumably this could be done in the Dockerfile); NGINX should then create it as a regular file
- Alternative, configure NGINX to additionally log either into an additiona log file or into a syslog port (in which case the exporter would have to be configured to accept syslog input).

**Comment by GrzegorzKaczan** [comment]
Oh i just realized, its the alpine-nginx base image that does the symlinking: https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L105

**Comment by GrzegorzKaczan** [comment]
The problem was idd symlink to the `/dev/stdout` done by the base alpine-nginx image itself.

Perfect, both solution worked. Not only got i a solution but got 2 :) and thanks for the swift response. Closing it now
