### ISSUE TITLE
Feature request: Be able to change `/metrics` endpoint

### ISSUE THREAD

**Issue by GrzegorzKaczan** [martin-helmich/prometheus-nginxlog-exporter#114]
**Issue type**:
> Feature request  

**What happened**:
Currently the exporter only exposes metrics under fixed `/metrics` endpoint which cannot be changed. My company enforces different endpoint name for the metrics so this blocks me from using this tool.

**What you expected to happen**:
Metrics endpoint is a option in configuration (defaults to `/metrics`)

**Configuration example**:
```
-metrics-endpoint=/my-custom-endpoint
```

**Comment by martin-helmich** [comment]
That shouldn't be too difficult ;) I'll see if I can find the time later.

**Comment by martin-helmich** [comment]
There you go, @GrzegorzKaczan. The change is included in release [1.6.0](https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/tag/v1.6.0).

**Comment by GrzegorzKaczan** [comment]
Awesome, thx!

**Comment by GrzegorzKaczan** [comment]
@martin-helmich 
I tried it on 1.6 release but it does not work, the default endpoint is taken even tho configuration seems to acknowledge my overridden endpoint. 

See screenshot:
![image](https://user-images.githubusercontent.com/1488502/80949346-2cb7c880-8df4-11ea-91cb-6087f9fc69b2.png)

**Comment by martin-helmich** [comment]
Ugh, I feel stupid... Yes, the custom metrics endpoint is in the configuration, but the _used_ endpoint is still hardcoded :facepalm: 

https://github.com/martin-helmich/prometheus-nginxlog-exporter/blob/03c21e11b92798dde91888b7984f62d08128e089/main.go#L204

**Comment by GrzegorzKaczan** [comment]
Sry to bother one more time but there is a bug still. It will work when endpoint is specified inline but not via config file. It's because of this line:
https://github.com/martin-helmich/prometheus-nginxlog-exporter/blob/847e2a6580e41a98c45c2375e83f49bcb244bf87/main.go#L149

You load opts with cfg defaults and the loadConfig happens after this. Hence, endpoint from config will never be respected.
You should `loadConfig` somewhere around `main.go:141` i guess.

**Comment by martin-helmich** [comment]
Yep, I acted somewhat hastily on that one 🙄. #117 now finally does correctly -- asserted by tests (which I should have added in the first place).

**Comment by GrzegorzKaczan** [comment]
Works now, thx.
