### ISSUE TITLE
Is consul a requirement?

### ISSUE THREAD

**Issue by remerle** [martin-helmich/prometheus-nginxlog-exporter#124]
Sorry if this should be clear, but it's not obvious how Consul is being used in the examples.  It seems specific-enough of an addition to make it seem like a requirement, but it's not obvious why service discovery would be needed.

**Comment by remerle** [comment]
I see there is an enable flag [in the config](https://github.com/martin-helmich/prometheus-nginxlog-exporter/blob/f60622ce5c7f38b301e44ddeeefd31dec09c9e60/config/structs.go#L41), so I'm guessing this is not required.

It may be worth calling that out in the documentation.  I'm happy to contribute the verbiage.

I'll leave this issue open just in case I missed something.

**Comment by martin-helmich** [comment]
No, Consul is indeed entirely optional and *not* a requirement. Happy to accept documentation fixes. 🙂
