### ISSUE TITLE
Configuration for enabling summaries and/or histograms

### ISSUE THREAD

**Issue by stempler** [martin-helmich/prometheus-nginxlog-exporter#127]
**Is your feature request related to a problem? Please describe.**
I was wondering about the metrics for response time and upstream time. There is for each both a summary and a histogram. The information collected in the summary is also contained in the histogram (sum and count). So there are two redundant time series for each combination of labels - at least that is my conclusion - let me know if I'm missing something.

**Describe the solution you'd like**
To keep backwards compatibility I guess the best solution would be to make it configurable, if summaries and/or histograms are collected. Then it would be up to the user to choose whether they want a summary or a histogram or even both (which would be the default behavior for backwards compatibility).

**Describe alternatives you've considered**
- To just get rid of the redundancy, the summaries could also just be removed. This would however not be backwards compatible (but probably what I would do on a fork if the first option is not implemented, given my lack of Go expertise).
- A backwards compatible way would be to add a configuration option to just disable the summary

**Comment by martin-helmich** [comment]
Yes, both histograms and summaries expose a `sum` and `count` metric that are indeed redundant. However, they do each export different metrics on top of those (a summary exports a set of streaming quantiles, whereas a histogram exports bucketed counts; see [the documentation](https://prometheus.io/docs/practices/histograms/) for more information on the distinction).

So I definitely see a use case for providing both metrics. Calculating both of them in the exporter does not make much of a difference in terms of resource consumption (unverified assumption, but I'm fairly confident), and if you really don't want them, you can always drop metrics at scrape time:

```yaml
   metric_relabel_configs:
   - source_labels: [ __name__ ]
     regex: 'undesired_metric_name'
     action: drop
```

For the time being, I'd prefer leaving this as-is. Feel free to let me know your thoughts on this, though.

**Comment by stempler** [comment]
I can see your point, I just wondered why both are there right now.

For the summary to produce the quantiles they need to be configured, which is not the case yet. Even if that was done I don't think that it would be a common use case to have a summary and a histogram at the same time, but as you say metrics can be skipped when scraped. Though as the documentation states *"Observations are expensive due to the streaming quantile calculation."*, so having the quantile calculation optional would make sense if that would ever be introduced.

Generally I think for the metrics on HTTP requests that are produced here, the histogram is clearly the favorite, as it allows you to aggregate time series and use a flexible sliding time-window for calculating quantiles (even if those may be less accurate than the ones the summary can produce) - but maybe that's also just the use cases I have in mind.
