### ISSUE TITLE
Promote "dynamic re-labeling" from "experimental" to "stable"

### ISSUE THREAD

**Issue by leobasilio** [martin-helmich/prometheus-nginxlog-exporter#132]
I'm really interested in using the dynamic re-labeling feature, but I'm afraid to do so because it's considered experimental. After looking around, it seems that the first commits related to this feature date back to early 2018. So how much of an experiment is it nowadays? How can we contribute to make it stable?

**Comment by martin-helmich** [comment]
>So how much of an experiment is it nowadays?

Not much of an experiment anymore, tbh. I was hesitant to ship the feature as "stable" because I didn't know how the feature would be used and wanted to reserve the option to introduce breaking changes into the configuration format.

IMO nothing speaks against officially declaring this feature "stable" with the next minor version.

If you're interested in using this feature *now*, I can assure with a reasonably high degree of certainty that the relabeling configuration syntax will not receive any breaking changes until then.

**Comment by leobasilio** [comment]
Thanks for your reply. I'm interested in finding slow routes in my application and I think extracting it straight from the access log would better reflect the end user's perception. In this application, we follow a `/controller/action/...` pattern. I could write a regex that would give me only the first two segments and use that as a label for my metric. I have written my own exporter for that, but it's really simple and yours is more feature-rich. It'd rather use it, but I was afraid the dynamic re-labeling could yield some unstable behavior.

**Comment by runzhliu** [comment]
Hi! @martin-helmich After I checked the source code, I found there is only the default separator as " ", I think it would be more configurable if we could choose whatever separator we need. 

```go
type RelabelConfig struct {
	TargetLabel  string              `hcl:",key" yaml:"target_label"`
	SourceValue string              `hcl:"from" yaml:"from"`
	Whitelist        []string           `hcl:"whitelist"`
	Matches        []RelabelValueMatch `hcl:"match"`
	Split               int                   `hcl:"split"`

	WhitelistExists bool
	WhitelistMap    map[string]interface{}
}
```

**Comment by martin-helmich** [comment]
Reopening. This should not have been closed.

**Comment by martin-helmich** [comment]
> Hi! @martin-helmich After I checked the source code, I found there is only the default separator as " ", I think it would be more configurable if we could choose whatever separator we need.

@runzhliu Sorry, I accidentally overlooked your -- absolutely reasonable -- suggestion. I've opened #149 to track that suggestion separately.
