### ISSUE TITLE
.deb install fails - couldn't find any package

### ISSUE THREAD

**Issue by cb3inco** [martin-helmich/prometheus-nginxlog-exporter#138]
**Describe the bug**
installation of .deb fails

**To Reproduce**
run - sudo apt install prometheus-nginxlog-exporter_1.7.1._linux_amd64.deb

**Expected behavior**
Expecting the deb file to install per instructions on gitlab.

administrator@server:~$ sudo apt install prometheus-nginxlog-exporter_1.7.1._linux_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package prometheus-nginxlog-exporter_1.7.1._linux_amd64.deb
E: Couldn't find any package by glob 'prometheus-nginxlog-exporter_1.7.1._linux_amd64.deb'
E: Couldn't find any package by regex 'prometheus-nginxlog-exporter_1.7.1._linux_amd64.deb'

**Environment**:

- Exporter version: 1.7.1
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Deployment method (e.g. Docker image, deb/rpm package, self-compiled, ...): .deb
- Others:

**Comment by cb3inco** [comment]
Ok I was able to get it installed by doing **sudo apt install ./prometheus-nginxlog-exporter_1.7.1._linux_amd64.deb** but I get some other warnings - should this be a concern?

sudo apt install ./prometheus-nginxlog-exporter_1.7.1_linux_amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'prometheus-nginxlog-exporter' instead of './prometheus-nginxlog-exporter_1.7.1_linux_amd64.deb'
The following NEW packages will be installed:
  prometheus-nginxlog-exporter
0 upgraded, 1 newly installed, 0 to remove and 48 not upgraded.
Need to get 0 B/4,224 kB of archives.
After this operation, 11.0 MB of additional disk space will be used.
Get:1 /home/administrator/prometheus-nginxlog-exporter_1.7.1_linux_amd64.deb prometheus-nginxlog-exporter amd64 1.7.1 [4,224 kB]
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 11 package 'prometheus-nginxlog-exporter':
 missing maintainer
Selecting previously unselected package prometheus-nginxlog-exporter.
(Reading database ... 104881 files and directories currently installed.)
Preparing to unpack .../prometheus-nginxlog-exporter_1.7.1_linux_amd64.deb ...
Unpacking prometheus-nginxlog-exporter (1.7.1) ...
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5151 package 'prometheus-nginxlog-exporter':
 missing maintainer
Setting up prometheus-nginxlog-exporter (1.7.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/prometheus-nginxlog-exporter.service → /lib/systemd/system/prometheus-nginxlog-exporter.service.


I also appear that I had the file name spelled wrong, but double checked and it still throws the original error in the first comment.

**Comment by martin-helmich** [comment]
When calling `apt install prometheus-nginxlog-exporter_1.7.1._linux_amd64.deb`, APT will search for a package of that exact name in its package repository (and consequently will not find any). By specifying the leading `./`, you instruct APT to install from a local file (alternatively, you could use `dpkg -i $filename` followed by `apt-get install -f`).

More information: https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt

The warnings when installing are a separate matter, though. They're easy enough to fix, and I'll leave this issue open until they are. Not harmful in any way, however.
