### ISSUE TITLE
Need label for request_uri 

### ISSUE THREAD

**Issue by koolay** [martin-helmich/prometheus-nginxlog-exporter#14]
It's necessary to know slow request_uri.

**Comment by martin-helmich** [comment]
This is a good idea in general, but needs a bit more thought before being implemented. Using the request URI directly as label value would introduce a label with an unbound set of values, resulting in a potentially infinite number of time series to be stored (something which Prometheus [is not really optimized for](https://prometheus.io/docs/practices/naming/#labels)).

Also, we'll need to consider dynamic URL parameters -- for instance, something like `/users/1234` and `/users/1235`, which should probably be subsumed under a label like `request_uri="/users/:id"`.

I'll see if I can come up with a nifty (and backwards-compatible) solution for this. Of course, I'm also open to suggestions.

**Comment by songjiayang** [comment]
yes, dynamic url is very important, I will try to realize it.
