### ISSUE TITLE
warning message with .deb package - missing "Maintainer" field

### ISSUE THREAD

**Issue by pellywog** [martin-helmich/prometheus-nginxlog-exporter#142]
**Describe the bug**
When I install the .deb package on Debian 11, I get the following warning message (I also get this message every time I install another package with apt later on)
```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 8305 package 'prometheus-nginxlog-exporter':
 missing 'Maintainer' field
```

**To Reproduce**
- Spawn a fresh debian 11
- Install the deb package from https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.6.0/prometheus-nginxlog-exporter_1.6.0_linux_amd64.deb
- run `apt-get install atop`

**Expected behavior**
There should be no such warning message - the Maintainer field should be filled out in the dpkg/status file.

**Environment**:

- Exporter version: `https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.6.0/prometheus-nginxlog-exporter_1.6.0_linux_amd64.deb`
- OS (e.g. from /etc/os-release): `Linux bullseye1 5.6.0-2-amd64 #1 SMP Debian 5.6.14-1 (2020-05-23) x86_64 GNU/Linux
`

**Comment by martin-helmich** [comment]
This was fixed in #139. Subsequently released versions will have the `maintainer` field set.
