### ISSUE TITLE
Ability to suppress log output for log line parse errors

### ISSUE THREAD

**Issue by rayrod2030** [martin-helmich/prometheus-nginxlog-exporter#143]
**Is your feature request related to a problem? Please describe.**
We are using the `prometheus-nginxlog-exporter` to parse nginx logs that contain `$request_time` and `$upstream_response_time` data which is working great.  Our problem is that not all of our log lines contain those two variables so whenever we encounter a log line that doesn't include those variables the exporter fails on `parser.ParseString` and sends an error message to stdout.  We process thousands of requests per second so even a small percentage of log lines that cannot be parsed represent a large amount of local log data to handle on instances we run this exporter on.

**Describe the solution you'd like**
I'd like a way to avoid writing out tons of log messages from the exporter for log lines that it cannot process.

Note: I've got a PR for this feature but I'd like to ask the question here first to get a feel for what we'd like this flag to do?

**Describe alternatives you've considered**
A workaround at the moment is to have your logging facility ignore the log messages but that can get tricky in our case as we log to `journald` and syslog and subsequently ship syslog data to our ELK stack so it's quite a bit to drop these messages and we'd still like to avoid all the local log file write and `logrotate` activity that is happening in order to keep the server from filing up it's disk.

**Comment by martin-helmich** [comment]
I get that this can be annoying. Any PRs in this direction would be most welcome. Do you already have any thoughts on how to approach this (I guess so, since you mentioned you already have a PR ready to go 😉)?

I'm wondering if it might make sense to switch from simply printing to stdout to a leveled logging library (logrus, glog, whatever), with the loglevel being controllable using a flag. 🤔

**Comment by rayrod2030** [comment]
My current PR has a simple flag called `disable-parse-error-logging` that when set simply keeps from writing out the parse error to stdout but keeps incrementing the `parseErrorsTotal` counter so you will still be able to detect a noticeable change from the norm for parse errors.  This is the simplest of changes but I totally agree that what we need is to implement leveled logging and just make the parse error a `WARN` or `INFO` and leave it up to the user to adjust their logging level accordingly.
