### ISSUE TITLE
Suggestion: new metric about tls protocol usage

### ISSUE THREAD

**Issue by smknstd** [martin-helmich/prometheus-nginxlog-exporter#155]
I recently enabled TLS1.3 on nginx, and I would like to get metrics on its usage. 

I think nginx lets you add the protocol used in every request to the access log :

```
        log_format ... $ssl_protocol ...
```

so it would be possible to count those.

What do you think of adding this as a new facultative metric ?

**Comment by martin-helmich** [comment]
This should already work using the [dynamic relabeling](https://github.com/martin-helmich/prometheus-nginxlog-exporter#dynamic-re-labeling) feature. The following configuration might work:

ˋˋˋ
relabel "ssl_protocol" {
  from = "ssl_protocol"

  # optional
  whitelist = [
    # possible ssl_protocols; if omitted, all values are allowed
  ]
}
ˋˋˋ

Let me know if that helps. 🚀

**Comment by smknstd** [comment]
Yes I think it can do the job, thanx !!!!
