### ISSUE TITLE
Incorect data when using access_log flush time in nginx

### ISSUE THREAD

**Issue by awronski** [martin-helmich/prometheus-nginxlog-exporter#156]
When setting access_log flush time in [nginx](http://nginx.org/en/docs/http/ngx_http_log_module.html) like:
`access_log /var/log/nginx/access.log  main buffer=1m flush=60s;`

The data looks incorrect. On `Grafana` they are very frayed.

I am not sure if this is a problem with `Prometheus`, `nginxlog-exporter` or my configuration.

It looks like the `Exporter` calculated data based on log incoming time instead of the times in log.

**Environment**:
`prometheus-nginxlog-exporter:v1.4.2`
`nginx/1.14.0 (Ubuntu)`

Thanks for help in advance,

**Comment by stempler** [comment]
> It looks like the Exporter calculated data based on log incoming time instead of the times in log.

That's correct. In the exporter default metric collectors like Counter/Histogram/Summary are used and the timestamp will actually be the one when Prometheus scrapes the exporter.
I guess the assumption here is that the processing of the logs in the exporter only has very little delay.

In principle the Prometheus format supports explicit timestamps, but even if the metric collectors would support that by default, the key is Prometheus scraping the exporter:
- if the logs are flushed every 60s, prometheus only can scrape new data every 60s
- there can only be one value and one timestamp associated with a given metric when it is being scraped (so you can't provide additional values for the past)

So as far as I can tell you will not be able to have a resolution that is more detailed than your flush interval.

**Comment by awronski** [comment]
Hi Simon,

Thanks for clarification.

> there can only be one value and one timestamp associated with a given metric when it is being scraped (so you can't provide additional values for the past)

I was thinking about the same thing. But was hoping that there is some workaround to smooth the data?

**Comment by stempler** [comment]
> I was thinking about the same thing. But was hoping that there is some workaround to smooth the data?

I guess you could change the scrape interval for that exporter in Prometheus to 60s and make sure that your Grafana dashboards reflect that as well, e.g. configure a minimum interval of 2 minutes (so always at least two data points are in the interval).

**Comment by martin-helmich** [comment]
Sorry for the delay. @stempler's assessment is entirely correct. To offer a higher metric time-resolution, the exporter would need to export these metrics with additional (past) timestamps, which would also need to be understood by Prometheus. I concur with the recommendation to adjust the scraping interval to your log file flush interval -- this won't increase the data resolution, but will at least smooth things a bit.

**Comment by martin-helmich** [comment]
Closing for now, as this is more of a conceptual issue for that no known solution exists. Feel free to comment/reopen if any other possible solutions or workarounds come to mind.
