### ISSUE TITLE
this works for "log_format json escape=json " ?

### ISSUE THREAD

**Issue by sitnovas** [martin-helmich/prometheus-nginxlog-exporter#157]
Good day, please tell me. There is a need to run the exporter with log_format of the json format will this work ?

Example:
log_format json escape=json '{ "@timestamp": "$time_iso8601", '
                   '"remote_addr": "$remote_addr", '
                   '"body_bytes_sent": "$body_bytes_sent", '
                   '"status": $status, '
                   '"request": "$request", '
                   '"url": "$uri", '
                   '"request_method": "$request_method", '
                   '"response_time": $temprt, '
                   '"http_referrer": "$http_referer", '
                   '"http_user_agent": "$http_user_agent" }';
 access_log  /log/access.log  json;

**Comment by martin-helmich** [comment]
Hey! :wave:  Sorry for the late response. This sounds similar to the JSON input support already requested in #93. I'm still happy to accept PRs in that matter. As a workaround, you _might_ be able to use something like the following configuration snippet (in the exporter configuration file):

```yaml
format: >
  { "@timestamp": "$time_iso8601", "remote_addr": "$remote_addr", ...
```

Of course, this does not substitute any real JSON parsing and will fail as soon as the field order or formatting (or anything, really) changes or the exporter encounters any JSON-specific escaping.
