### ISSUE TITLE
No metrics show up when i curl 

### ISSUE THREAD

**Issue by pkvel01** [martin-helmich/prometheus-nginxlog-exporter#159]
OS : Centos 7

Config.yml
listen:
  port: 4040
  address: "xx.xx.xx.xx"
  metrics_endpoint: "/metrics"

namespaces:
  - name: nginx
    source:
      files:
        - /home/user/access1.log
    format: "$time_iso8601\t$hostname\t$remote_addr:$remote_port\t$upstream_addr\t$request_time\t-\t-\t$status\t$upstream_status\t$request_length\t$body_bytes_sent\t$request\t$upstream_http_x_apigee_message_id\t$http_user_agent\t$host\t$hostname-$pid-$connection-$connection_requests\t$http_x_forwarded_for"

    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]

user@noc.net:~# curl -v "http://localhost:4040/metrics"
* About to connect() to localhost port 4040 (#0)
*   Trying 10.64.159.168...
* Connected to localhost port 4040 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhst:4040
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Tue, 24 Nov 2020 03:42:58 GMT
< Content-Length: 155
<
# HELP nginx_parse_errors_total Total number of log file lines that could not be parsed
# TYPE nginx_parse_errors_total counter
nginx_parse_errors_total 0

**Comment by martin-helmich** [comment]
I cannot reproduce this with the given information. Please state the exporter version you're using, post any stdout output of the exporter process itself and ideally provide an (anonymized) example access log file.

**Comment by pkvel01** [comment]
Using the latest version 1.8 of exporter

./prometheus-nginxlog-exporter -config-file config.yml
loading configuration file config.yml
using configuration {Listen:{Port:4040 Address:xx.xx.xx.xx MetricsEndpoint:/metrics} Consul:{Enable:false Address: Datacenter: Scheme: Token: Service:{ID: Name:bels:map[] MetricsOverride:<nil> NamespacePrefix: SourceFiles:[] SourceData:{Files:[/home/xxxx/nginxlogexporter/prometheus-nginxlog-exporter-master/access-1.loe\t\t$upstream_addr\t$request_time\t"-"\t"-"\t$status\t$upstream_status\t$request_length\t$bytes_body\t\"$request\"\t\"$upstream_http_x_apigee_message_id\"\t$http_var_xff\t"-"\t"-"\t"-"\t"-"\t"-"\t"-"\t$upstream_http_x_apigee_dp_color\t$my_x_apigee_target_latency\t\"$upstream_http_x_apigee_proxy\"\t\"$upstream_http_x_apigebelConfigs:[] HistogramBuckets:[0.005 0.01 0.025 0.05 0.1 0.25 0.5 1 2.5 5 10] PrintLog:true OrderedLabelNames:[] OrderedLabelValues:[]}] EnableExperimentalFeatur
starting listener for namespace nginx
running HTTP server on address 10.64.159.168:4040, serving metrics at /metrics
2020/11/26 18:32:44 Seeked /home/xxx/nginxlogexporter/prometheus-nginxlog-exporter-master/access-1.log - &{Offset:0 Whence:2}

Log file 

2020-11-23T17:00:10-08:00       rmp01..xx.inc.net xx.yy.zz.aa:38242      xx.yy.aa.ii:8998       0.003   -       -       200     200     1743    10      POST /v1/frontends/clients/xx1/applications/default/interactions HTTP/1.1     rmp01.xx-inc.net-4681-91395376-4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36  api.yy-inc.net rmp01.xx-inc.net-4681-91395376-4 34.68.221.121, 10.65.189.248    -       -       -       -       -       -       green   2       /organizations/xxxcustomer/environments/prod/apiproxies/ude-frontends        /v1/frontends   dc-1    gateway-1       green   -       gateway-1       dc-1
2020-11-23T17:00:12-08:00       rmp01.xx-inc.net xx.yy.xa.57:36066      aa.ba.yc55:8998       0.011   -       -       200     200     1550    10      POST /v1/frontends/clients/xxx1/applications/xxxx/interactions HTTP/1.1    rmp01.xx-inc.net-4684-91395453-5 Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1    api.xxx-inc.net rmp01.xx-inc.net-4684-91395453-5 63.225.87.110, 10.65.189.248    -       -       -       -       -       -   green    2       /organizations/xxxcustomer/environments/prod/apiproxies/ude-frontends   /v1/frontends   dc-1    gateway-1       green   -       gateway-1       dc-1
2020-11-23T17:00:12-08:00       rmp01.xx-inc.net xx.yy.xa.51:51014      aa.ba.yc55:8998       0.009   -       -       200     200     40002   304     POST /v1/analytics/events HTTP/1.1   rmp01.xx-inc.net-4688-91395629-1 -       api.xxx-inc.net rmp01.xx-inc.net-4688-91395629-1 xx.uu.uz.cv, po.ol.oo.pp     -       -       -       -       -   -green   2       /organizations/xxxcustomer/environments/prod/apiproxies/analytics       /v1/analytics   dc-1    gateway-1       green   -       gateway-1       dc-1

**Comment by pkvel01** [comment]
> Using the latest version 1.8 of exporter
> 
> ./prometheus-nginxlog-exporter -config-file config.yml
> loading configuration file config.yml
> using configuration {Listen:{Port:4040 Address:xx.xx.xx.xx MetricsEndpoint:/metrics} Consul:{Enable:false Address: Datacenter: Scheme: Token: Service:{ID: Name:bels:map[] MetricsOverride: NamespacePrefix: SourceFiles:[] SourceData:{Files:[/home/xxxx/nginxlogexporter/prometheus-nginxlog-exporter-master/access-1.loe\t\t$upstream_addr\t$request_time\t"-"\t"-"\t$status\t$upstream_status\t$request_length\t$bytes_body\t"$request"\t"$upstream_http_x_apigee_message_id"\t$http_var_xff\t"-"\t"-"\t"-"\t"-"\t"-"\t"-"\t$upstream_http_x_apigee_dp_color\t$my_x_apigee_target_latency\t"$upstream_http_x_apigee_proxy"\t"$upstream_http_x_apigebelConfigs:[] HistogramBuckets:[0.005 0.01 0.025 0.05 0.1 0.25 0.5 1 2.5 5 10] PrintLog:true OrderedLabelNames:[] OrderedLabelValues:[]}] EnableExperimentalFeatur
> starting listener for namespace nginx
> running HTTP server on address 10.64.159.168:4040, serving metrics at /metrics
> 2020/11/26 18:32:44 Seeked /home/xxx/nginxlogexporter/prometheus-nginxlog-exporter-master/access-1.log - &{Offset:0 Whence:2}
> 
> Log file
> 
> 2020-11-23T17:00:10-08:00 rmp01..xx.inc.net xx.yy.zz.aa:38242 xx.yy.aa.ii:8998 0.003 - - 200 200 1743 10 POST /v1/frontends/clients/xx1/applications/default/interactions HTTP/1.1 rmp01.xx-inc.net-4681-91395376-4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36 api.yy-inc.net rmp01.xx-inc.net-4681-91395376-4 34.68.221.121, 10.65.189.248 - - - - - - green 2 /organizations/xxxcustomer/environments/prod/apiproxies/ude-frontends /v1/frontends dc-1 gateway-1 green - gateway-1 dc-1
> 2020-11-23T17:00:12-08:00 rmp01.xx-inc.net xx.yy.xa.57:36066 aa.ba.yc55:8998 0.011 - - 200 200 1550 10 POST /v1/frontends/clients/xxx1/applications/xxxx/interactions HTTP/1.1 rmp01.xx-inc.net-4684-91395453-5 Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1 api.xxx-inc.net rmp01.xx-inc.net-4684-91395453-5 63.225.87.110, 10.65.189.248 - - - - - - green 2 /organizations/xxxcustomer/environments/prod/apiproxies/ude-frontends /v1/frontends dc-1 gateway-1 green - gateway-1 dc-1
> 2020-11-23T17:00:12-08:00 rmp01.xx-inc.net xx.yy.xa.51:51014 aa.ba.yc55:8998 0.009 - - 200 200 40002 304 POST /v1/analytics/events HTTP/1.1 rmp01.xx-inc.net-4688-91395629-1 - api.xxx-inc.net rmp01.xx-inc.net-4688-91395629-1 xx.uu.uz.cv, po.ol.oo.pp - - - - - -green 2 /organizations/xxxcustomer/environments/prod/apiproxies/analytics /v1/analytics dc-1 gateway-1 green - gateway-1 dc-1

**Comment by pkvel01** [comment]
i would like someone to take a look and help, please dont close the issue

**Comment by ramaseshan-edgenetworks** [comment]
I have also been trying with the latest release and facing similar issues. I will soon post sample log files and the config used for further debugging.

**Comment by ramaseshan-edgenetworks** [comment]
Sample Log file : [sample_access.log](https://github.com/martin-helmich/prometheus-nginxlog-exporter/files/5892345/sample_access.log)



Here is my log format 

`        log_format apm '"$time_local" client=$remote_addr '
               'method=$request_method request="$request" '
               'request_length=$request_length '
               'status=$status bytes_sent=$bytes_sent '
               'body_bytes_sent=$body_bytes_sent '
               'referer=$http_referer '
               'user_agent="$http_user_agent" '
               'upstream_addr=$upstream_addr '
               'upstream_status=$upstream_status '
               'request_time=$request_time '
               'upstream_response_time=$upstream_response_time '
               'upstream_connect_time=$upstream_connect_time '
               'upstream_header_time=$upstream_header_time';
`


And I am running the exporter like this .

`prometheus-nginxlog-exporter --format="\"$time_local\" client=$remote_addr method=$request_method request=\"$request\" request_length=$request_length  status=$status bytes_sent=$bytes_sent body_bytes_sent=$body_bytes_sent referer=$http_referer user_agent=\"$http_user_agent\" upstream_addr=$upstream_addr upstream_status=$upstream_status request_time=$request_time upstream_response_time=$upstream_response_time upstream_connect_time=$upstream_connect_time upstream_header_time=$upstream_header_time" sample_access.log`


Other details : 
OS : Ubuntu 20.04 LTS  
Installed via the deb package  

The response I am getting 

![image](https://user-images.githubusercontent.com/75010031/106246914-dbc6ea80-6234-11eb-8b10-ed49d75f9bf5.png)

**Comment by ramaseshan-edgenetworks** [comment]
@martin-helmich  Let me know if you need anything more specific to understand this issue. Will be happy to provide the necessary information.

**Comment by ramaseshan-edgenetworks** [comment]
@martin-helmich  Let me know if you need more info.

**Comment by martin-helmich** [comment]
Sorry, lost track of this one. I'll investigate this issue using the input you've provided as soon as I find the time.

**Comment by ramaseshan-edgenetworks** [comment]
@martin-helmich Any luck with this one ?

**Comment by frenkye** [comment]
Dunno, seems like you have wrong format don't know why you have `\t` in there just use
```
'$time_iso8601 $hostname $remote_addr:$remote_port $upstream_addr $request_time - - $status $upstream_status $request_length $body_bytes_sent $request $upstream_http_x_apigee_message_id $http_user_agent $host $hostname-$pid-$connection-$connection_requests $http_x_forwarded_for'
```

I tried it on dummy log like:
```
echo "2020-11-23T17:00:10-08:00 rmp01..xx.inc.net xx.yy.zz.aa:38242 xx.yy.aa.ii:8998 0.003 - - 200 200 1743 10 POST /v1/frontends/clients/xx1/applications/default/interactions HTTP/1.1 rmp01.xx-inc.net-4681-91395376-4 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36 api.yy-inc.net rmp01.xx-inc.net-4681-91395376-4 34.68.221.121, 10.65.189.248 - - - - - - green 2 /organizations/xxxcustomer/environments/prod/apiproxies/ude-frontends /v1/frontends dc-1 gateway-1 green - gateway-1 dc-1" >> /tmp/nginx.log
```

Btw you need to do some write into the log for data to show.

**Comment by martin-helmich** [comment]
In case of a bad format, the `{whatever}_parse_errors` counter metric should increase (in addition to errors being printed on STDERR).

> Btw you need to do some write into the log for data to show.

Picking up on what @frenkye said: Keep in mind that _existing_ contents of log files will not be exported as metrics (if the exporter did that, historic data would be scraped with a current timestamp, which would just produce wrong results). The exporter will only export metrics from log lines that are written _after_ it is started.
