### ISSUE TITLE
Set label value from a format variable

### ISSUE THREAD

**Issue by sethryder** [martin-helmich/prometheus-nginxlog-exporter#16]
I know this would be something you would have to be very careful with so you didn't flood your prometheus server with a very large amount of metrics but would it be possible to set a label from a format variable?

For example if you have multiple hosts (server blocks) that feed into a single access log, so it would be nice if I could add a label based on the host. 

For example something like:

```
namespace "em" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $remote_addr $http_x_forwarded_for $host $upstream_addr"
  source_files = [
    "/var/log/nginx/access.log"
  ]
  labels {
    host = $host
  }
}
```

Again I know this could end badly depending on what variable you used so I understand if this is something you would want to avoid, but figured I would bring it up anyways.

Thanks!

**Comment by martin-helmich** [comment]
Thanks for the suggestion! I can see how this would be useful; however, even using a variable with a (supposedly) bound set of values like `$host` might backfire, as it basically contains just the value of the HTTP `Host` header (allowing your users to spam your metrics server with arbitrary values, at the extreme even causing a DoS).

If it's specifically the `$host` header that you're interested in, I would prefer adding an option to add the `$host` value as a label, as long as a whitelist of allowed values is supplied in the configuration (then, each `$host` value could be bucketed in each of the supplied values, along with a `host="other"` value, or similar). Let me know your thoughts on this, @sethryder.

**Comment by sethryder** [comment]
@martin-helmich good point, I did not think of that.

I think what you mentioned of having a configuration option along with a providing a whitelist of allowed values would work well.

Thanks for the quick response.

**Comment by sethryder** [comment]
Just to add another note here,

Another option I could think of as well if also supporting $server_name as an option in labels, since that would be a set list/amount. Ran across it while looking at a  mtail example configuration for nginx: https://github.com/ipfs/infrastructure/blob/master/mtail/progs/nginx.mtail .

**Comment by songjiayang** [comment]
@sethryder  you can have a try [nginx-log-exporter](https://github.com/songjiayang/nginx-log-exporter)
