### ISSUE TITLE
./prometheus-nginxlog-exporter: cannot execute binary file

### ISSUE THREAD

**Issue by tetlika** [martin-helmich/prometheus-nginxlog-exporter#162]
when I try to use 1.3.0 or 1.8.0 exporter Im getting error:
./prometheus-nginxlog-exporter: cannot execute binary file

Im on centos

**Comment by martin-helmich** [comment]
Please state how you have installed the exporter and how you are invoking it (Docker container, DEB package, binary download, self-compiled, ...?).
