### ISSUE TITLE
Bytes received metric

### ISSUE THREAD

**Issue by greenstatic** [martin-helmich/prometheus-nginxlog-exporter#165]
Great exporter. 

Besides the `http_response_size_bytes` it would be great if there was a `http_request_size_bytes` metric. The only downside would be the requirement to add to Nginx logs the [$request_length](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_length) variable, but we can make it an optional metric like `http_response_size_bytes`.

**Comment by martin-helmich** [comment]
:+1: Great idea! I'll get to this when I can. In the meantime, PRs are always welcome.
