### ISSUE TITLE
Does the binary works on Alpine Linux?

### ISSUE THREAD

**Issue by omata** [martin-helmich/prometheus-nginxlog-exporter#17]
Hello,

Does the compiled binary works on alpine linux? I want to get it running into a docker container. I will use Alpine Linux. BTW I do not know anything about `go` but I want to ask, How I can compile the binary by my own?

Best regards,

**Comment by martin-helmich** [comment]
The current binaries provided at this project's "Releases" page are not compiled statically and are linked against glibc in version 6. They won't work with Alpine's musl libc.

You can create a static binary by compiling like this:

    $ CGO_ENABLED=0 go build -a -installsuffix cgo

**Comment by martin-helmich** [comment]
@omata I've added a statically linked binary to the [latest release](https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/tag/v1.0.1). All future releases should be compiled entirely statically by default (and thus be compatible to be run on Alpine Linux).

**Comment by omata** [comment]
@martin-helmich Thank you very much!! 😄
