### ISSUE TITLE
Feature: support $upstream_cache_status for cache statistics

### ISSUE THREAD

**Issue by the-infinity** [martin-helmich/prometheus-nginxlog-exporter#172]
In order to create cache statistics it would nice to get the cache status in $upstream_cache_status. [According to documentation](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_cache_status) this can be “MISS”, “BYPASS”, “EXPIRED”, “STALE”, “UPDATING”, “REVALIDATED”, or “HIT”.

My knowledge in Go is very very limited, so maybe a PR is not the best idea, but still I think this could give very interesting statistics in environments with caching ... :)

**Comment by martin-helmich** [comment]
Adding the cache status as a label can already be done using [dynamic re-labeling](https://github.com/martin-helmich/prometheus-nginxlog-exporter#dynamic-re-labeling). If the `$upstream_cache_status` variable is present in your log format, the following configuration should work:

```hcl
namespace "foo" {
  // [...]

  relabel "cache_status" {
    from = "upstream_cache_status"
    whitelist = ["MISS", "BYPASS", "EXPIRED", "STALE", "UPDATING", "REVALIDATED", "HIT"]
  }
}
```

Let me know if that helps!
