### ISSUE TITLE
Can't setup the syslog input

### ISSUE THREAD

**Issue by itshikanov** [martin-helmich/prometheus-nginxlog-exporter#184]
**Describe the bug**
Do not read syslog input.

**Config**
version: 1.8.0

cat config.hcl 

    listen {
      port = 4040
    }

    namespace "nginx" {
      source = {
        syslog {
          listen_address = "udp://127.0.0.1:8513"
          format = "auto"
        }
      }

    format = "$remote_addr\t$remote_user\t$request\t$status\t$body_bytes_sent\t$http_referer\t$http_user_agent\t$http_x_forwarded_for"
    }

**Nginx config:**

log_format syslog_format  '$remote_addr\t$remote_user\t$request\t$status\t$body_bytes_sent\t$http_referer\t$http_user_agent\t$http_x_forwarded_for';
....
access_log syslog:server=127.0.0.1:8513,facility=local7,tag=nginx,severity=info syslog_format;

**syslog string  from ngrep:**

U 127.0.0.1:57279 -> 127.0.0.1:8513 #1034

  <190>Feb 18 09:11:00 test-k8s-1 nginx: 185.132.196.98.-.HEAD / HTTP/1.1.200.0.-.curl/7.58.0.-

**String from strace:**
`
[pid  1669] <... recvfrom resumed> "<190>Feb 18 09:11:48 test-k8s-1 nginx: 185.132.196.98\t-\tHEAD / HTTP/1.1\t200\t0\t-\tcurl/7.58.0\t-", 65536, 0, {sa_family=AF_INET, sin_port=htons(57279), sin_addr=inet_addr("127.0.0.1")}, [112->16]) = 93
`

**Result**:
 HELP nginx_parse_errors_total Total number of log file lines that could not be parsed
TYPE nginx_parse_errors_total counter
nginx_parse_errors_total 0

What wrong?

**Comment by martin-helmich** [comment]
Closed in favor of #183 -- please open only _one_ issue/question.
