### ISSUE TITLE
Provide JSON definiton for Grafana dashboard?

### ISSUE THREAD

**Issue by fujianan** [martin-helmich/prometheus-nginxlog-exporter#19]

**Comment by martin-helmich** [comment]
Please post in English.

**Comment by fujianan** [comment]
Can you  provide the json file of this nginx exporter performance in grafana ,Thank you !

**Comment by martin-helmich** [comment]
>My English is not Good!

...but still better than my Chinese. :)

I'm not entirely sure which Grafana dashboard you're referring to; are you referring to the one shown in my [blog article on this exporter](https://www.martin-helmich.de/en/blog/monitoring-nginx.html)? I don't have the JSON for that dashboard at hand right now, because it's running in a private network. But at least you can find the PromQL queries for getting the raw data out of Prometheus in that article:

>The diagrams in the screenshot above were generated from the following Prometheus queries:
>
>- Average response time: `sum(rate(app_http_response_time_seconds_sum[5m])) by (instance) / sum(rate(app_http_response_time_seconds_count[5m])) by (instance)`
>- Requests per second: `sum(rate(app_http_response_time_seconds_count[1m])) by (instance)`
>- Response time (90% quantile): `app_http_response_time_seconds{quantile="0.9",method="GET",status="200"}`
>- HTTP traffic: `sum(rate(app_http_response_size_bytes[5m])) by (instance)`
>- Status codes per second: `sum(rate(app_http_response_count_total[1m])) by (status)`

Let me know if that helps.

**Comment by fujianan** [comment]
Thanks for your  answer !
 I have read your  blog and did them but  I can't get the values 
I use the same configuration as yours

**Comment by fujianan** [comment]
<img width="811" alt="11" src="https://user-images.githubusercontent.com/22000011/34428222-7f493542-ec85-11e7-99b2-e0c7fa582e4a.png">
this is the metrics of nginx exporter   picture

And I created a graph in grafana to show the data ,But it didn't work !
like this picture
<img width="1246" alt="22" src="https://user-images.githubusercontent.com/22000011/34428410-7614900a-ec87-11e7-83d4-3e3cd05da37e.png">

Then  I   wanted to show the data:
sum(rate(app_http_response_time_seconds_sum[5m])) by (instance) / sum(rate(app_http_response_time_seconds_count[5m])) by (instance)

But  there was no data  like this 
<img width="1419" alt="33" src="https://user-images.githubusercontent.com/22000011/34428480-11f299e0-ec88-11e7-8b01-cf6107bb9c4e.png">

I guess  maybe the  the grammar of  query  is not correct or can't match 
Can you help me ?
And now  the place where you live maybe is night, I am sorry to bother you !
and if you can find the json file, can you provide it for me?

**Comment by martin-helmich** [comment]
Could you share your confiuration file (if you're using one) and the command-line flags you're starting the exporter with?

Keep in mind that the metrics are not necessarily named `app_*` like in my examples, but might be named differently depending on configuration (something that was already requested to be changed in #13).

**Comment by martin-helmich** [comment]
Closing for now. I've added a [FAQ section to the README](https://github.com/martin-helmich/prometheus-nginxlog-exporter#frequently-asked-questions) that contains some common issues and their causes that you might want to check. Feel free to re-open this issue, should your problem persist.
