### ISSUE TITLE
histogram count bug

### ISSUE THREAD

**Issue by frenkye** [martin-helmich/prometheus-nginxlog-exporter#192]
**Describe the bug**
Histogram bucket calculation seems to be counting request to multiple buckets. In way how histogram should works this is wrong.

**To Reproduce**
Prepare basic vhost in nginx and run:
```
while true
do
curl -H "Host: test-one.cz" http://<yourIP>/test
sleep 2
done
```

**Expected behavior**
the metric should be like this, current output bellow:
```
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="0.2"} 30
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="0.5"} 0
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="2"} 0
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="5"} 0
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="10"} 0
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="+Inf"} 0
```

**Configuration file** (remove section, if not applicable):

```
listen {
  port = 6114
  address = "0.0.0.0"
}
# Running from grains.nginx info and custom alter via pillars
namespace "nginx11" {
  metrics_override = { prefix = "nginxlog" }
  namespace_label = "orig_namespace"
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $host [$server_name] $request_time $request_length $remote_port $upstream_cache_status \"$http_range\" $upstream_response_time"
  source {
    files = [ "/home/www/test-one.cz/_log/nginx/access.log" ]
  }
  labels {
    cfg = "/etc/nginx/sites-enabled/test-one.cz"
    logfile = "/home/www/test-one.cz/_log/nginx/access.log"
  }
  histogram_buckets =  [.2, .5, 2, 5, 10]
}
```

**Example log file** (remove section, if not applicable):

```
# Insert some sample access logs that help reproduce the behavior
# IMPORANT: Please make sure to anonymize any PII like IP addresses and usernames!
```
0.0.0.0 - - [25/Mar/2021:13:47:32 +0100] "GET /test HTTP/1.1" 404 162 "-" "curl/7.64.1" test-one.cz [test-one.cz] 0.000 79 54236 - "-" -
0.0.0.0 - - [25/Mar/2021:13:47:37 +0100] "GET /test HTTP/1.1" 404 162 "-" "curl/7.64.1" test-one.cz [test-one.cz] 0.000 79 54237 - "-" -
0.0.0.0 - - [25/Mar/2021:13:47:43 +0100] "GET /test HTTP/1.1" 404 162 "-" "curl/7.64.1" test-one.cz [test-one.cz] 0.000 79 54238 - "-" -
0.0.0.0 - - [25/Mar/2021:13:47:48 +0100] "GET /test HTTP/1.1" 404 162 "-" "curl/7.64.1" test-one.cz [test-one.cz] 0.000 79 54241 - "-" -
```
# Please post the output of the exporter's /metrics endpoint, if applicable
```
nginxlog_http_response_count_total{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404"} 30

nginxlog_http_response_size_bytes{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404"} 4860

nginxlog_http_response_time_seconds{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",quantile="0.5"} 0
nginxlog_http_response_time_seconds{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",quantile="0.9"} 0
nginxlog_http_response_time_seconds{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",quantile="0.99"} 0
nginxlog_http_response_time_seconds_sum{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404"} 0
nginxlog_http_response_time_seconds_count{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404"} 30

nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="0.2"} 30
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="0.5"} 30
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="2"} 30
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="5"} 30
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="10"} 30
nginxlog_http_response_time_seconds_hist_bucket{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404",le="+Inf"} 30
nginxlog_http_response_time_seconds_hist_sum{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404"} 0
nginxlog_http_response_time_seconds_hist_count{cfg="/etc/nginx/sites-enabled/test-one.cz",logfile="/home/www/test-one.cz/_log/nginx/access.log",method="GET",orig_namespace="nginx11",status="404"} 30

nginxlog_parse_errors_total{orig_namespace="nginx11"} 0
```
# Please post the output of the exporter itself, if applicable
```

**Environment**:
Latest (1.8) and seen also on version before 1.7 (with the namespace change)
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION="10 (buster)"
```
- Deployment method (e.g. Docker image, deb/rpm package, self-compiled, ...): 
manually upack tar and run via supervisord
```
[program:nginxlog_exporter_6114]
command=/opt/prometheus/bin/nginxlog_exporter -config-file /opt/prometheus/conf/nginxlog_exporter.hcl
numprocs=1
autostart=True
autorestart=True

logfile_backups=4
stdout_logfile=/opt/prometheus/logs/exporters/%(program_name)s.out.log
stderr_logfile=/opt/prometheus/logs/exporters/%(program_name)s.err.log
```

**Comment by stempler** [comment]
I would say it works as expected - this is how histograms in Prometheus work. To quote [How does a Prometheus Histogram work?](https://www.robustperception.io/how-does-a-prometheus-histogram-work):

> The interesting part of the histogram are the `_bucket` time series, which are the actual histogram part of the histogram. More particularly they're counters which form a cumulative histogram, `le` stands for less than or equal to.

**Comment by martin-helmich** [comment]
Full ACK on what @stempler says. This is by design -- every Prometheus histogram is a [cumulative histogram](https://en.wikipedia.org/wiki/Histogram#Cumulative_histogram). In addition to the link already provided, also see the [the documentation](https://prometheus.io/docs/concepts/metric_types/#histogram) for more information.
