### ISSUE TITLE
Log-exporter RAM consumption never stops to increase

### ISSUE THREAD

**Issue by Aleporro13** [martin-helmich/prometheus-nginxlog-exporter#199]
Hi there Martin,

We have installed nginx-log-exporter v1.8.0 using docker-composed.

We're facing RAM consumption issues for the docker container as the memory consumed by nginx-log-exporter never stops to increase. The process itself seems to stores its statistics in the RAM, it does not use the hard disk like other processes or DBs to store data. This means that as it runs it will consume more and more RAM as we don't found the way to release or delete from RAM the data/statistics already sent to Prometheus.

This is the HCL config file we ran at this time:

listen {
  port = 4040
  metrics_endpoint = "/metrics"
}

enable_experimental = true

namespace "sni" {
  format = "$upstream_response_time\t$remote_addr\t$remote_user\t$time_iso8601\t$request\t$status\t$body_bytes_sent\t$http_user_agent\t$http_x_forwarded_for\t$msec\t$request_time\t$https\t"
  source {
    files = [
      "/mnt/nginx/logs/access.log"
    ]
  }

  print_log = false

  labels {
    environment = "client"
    host = "sni_router01"
  }

  relabel "request_uri" {
    from = "request"
    split = 2

    match "^/metadata/.*/btv/products.*" {
      replacement = "btv_products"
    }
    match "^/metadata/.*/btv/programmes.*" {
      replacement = "btv_programmes"
    }
  }

  relabel "client_ip" { from = "remote_addr" }
  relabel "user_agent" { from = "http_user_agent" }
  relabel "http_code" { from = "status" }

  histogram_buckets = [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
}

By limiting the container to 800Mbs of RAM, this is being consumed in less than a day, so we're running out of RAM in the whole server in just one day. 
Do you see the way we can release periodically the amount of RAM consumed?

By the way, nginx hourly logs reach as maximum 4MBs.

Thank you very much in advance for your support!

**Comment by martin-helmich** [comment]
Hey there,

I would *strongly discourage* using fields like the client IP or user agent as labels. The exporter will aggregate time series by label values, but with these labels, you create an (effectively) unbound set of possible label values (and therefore a potentially unlimited amount of time series), effectively disabling any aggregation almost completely.

Instead, I'd only recommend using labels with a clearly defined and bound set of possible values (like HTTP status codes), or using patterns+substitutions to reduce an unbound value set to a bound set of few known values.

**Comment by Aleporro13** [comment]
Thanks a lot Martin for your quick answer!

We'll effectively delete the 'relabel' for client_Ips and user_agents and keep only http_code as this would come with a much small set of different values.

Keep you posted after our tests!

**Comment by Aleporro13** [comment]
Thanks a lot for your response @martin-helmich . It was really helpful and now resources consumption is working quite better!
