### ISSUE TITLE
Metrics for $ssl_protocol and $ssl_cipher?

### ISSUE THREAD

**Issue by saz** [martin-helmich/prometheus-nginxlog-exporter#200]
**Is your feature request related to a problem? Please describe.**
I don't see any way to add additional metrics for e.g. ssl_protocol and ssl_cipher

**Describe the solution you'd like**
It would be great to configure metrics dynamically or, if that's not possible, to add additional metrics for ssl_protocol, ssl_cipher and maybe user agents.
I'd like to add a graph to my prometheus/grafana setup, which shows usages of the different ssl_protocols and ssl_ciphers.

**Describe alternatives you've considered**
Using something like goaccess is possible, but it's completely separate

**Comment by martin-helmich** [comment]
As long as `ssl_protocol` and `ssl_cipher` show up in your access log, you can [add them as labels via configuration](https://github.com/martin-helmich/prometheus-nginxlog-exporter#dynamic-re-labeling).

Hope that helps!
