### ISSUE TITLE
Add "--version" flag

### ISSUE THREAD

**Issue by andreymal** [martin-helmich/prometheus-nginxlog-exporter#205]
I want to use something like `prometheus-nginxlog-exporter --version` to check which version is currently installed and whether it needs to be updated.

It seems there is a ready-to-use module [prometheus/common/version](https://github.com/prometheus/common/blob/main/version/info.go) which also provides `build_info` metric (however I'm not sure if it can be used as is because it's "without any stability guarantees for external usage")

**Comment by andreymal** [comment]
@helmich-bot some activity special for you

**Comment by martin-helmich** [comment]
@andreymal Sorry for the spam and for the delayed response. This is an entirely sensible suggestion -- I just haven't gotten around to this, yet. 👍

**Comment by saz** [comment]
@martin-helmich Any news on this? Would be really helpful to keep the exporter up-to-date

> It seems there is a ready-to-use module [prometheus/common/version](https://github.com/prometheus/common/blob/main/version/info.go) which also provides `build_info` metric (however I'm not sure if it can be used as is because it's "without any stability guarantees for external usage")

It also requires the usage of [promu](https://github.com/prometheus/promu)
