### ISSUE TITLE
upstreamSeconds  and responseSeconds data type defined Histogram should be better?

### ISSUE THREAD

**Issue by songjiayang** [martin-helmich/prometheus-nginxlog-exporter#21]
Sometimes our service running on multiple Nginx, if we use `Histogram` type , web can calculate with Prometheus server.

**Comment by martin-helmich** [comment]
That's a good idea, although I'm hesitant to just change the metric type, as that might break existing dashboards and alerts for some people (including myself). I could imagine adding these as _new_ metrics, though. What do you think?

**Comment by martin-helmich** [comment]
@songjiayang I've opened up a pull request for this feature in #22. Feel free to give it a test and let me know if it suits your needs.

**Comment by songjiayang** [comment]
thank you very much and.

and I write a new exporter  https://github.com/songjiayang/nginx-log-exporter, inspired by you too much, thanks again.
