### ISSUE TITLE
Ability to group HTTP status by group, example 2xx, 3xx to reduce number of series per metric

### ISSUE THREAD

**Issue by truong-hua** [martin-helmich/prometheus-nginxlog-exporter#211]
**Is your feature request related to a problem? Please describe.**
In cloud prometheus or related, there may be a implied limit number of series per metric, and our `<namespace>_http_upstream_time_seconds_hist` can easily to reach that limit in high traffic system. This would also boost the query performance alot.

**Describe the solution you'd like**
We should group the HTTP status label to it's group by default and may be add a feature to allow user to activate individual HTTP status metrics by providing their expected HTTP status, such as `<namespace>_http_upstream_time_by_status_seconds_hist`

**Describe alternatives you've considered**
The easiest way is to upgrade the prometheus cloud

**Comment by martin-helmich** [comment]
Hey @truong-hua 👋 -- thanks for your suggestion. If I understand correctly, your suggestion is to drop the `status` label by default (or to map its set of values to a lower cardinality)? That would be a massively breaking change that I would very much prefer to avoid.

I'd be open to accepting PRs that add the proposed grouping (presumably by grouping status codes to something like `2xx` and similar?) as an opt-in feature (maybe to be activated via the configuration file), though.

Alternatively, you might think about a setup using [Prometheus Federation](https://prometheus.io/docs/prometheus/latest/federation/) and recording rules, in which you have a local Prometheus cluster that scrapes your targets and retains data at a high level of detail and a global Prometheus cluster that only stores aggregated data, but for a higher retention period.

**Comment by jbrandhorst** [comment]
If anyone else stumbles across this issue, I accomplished this by using an nginx map to create a variable that parses out just the first digit of the response code. That variable is then passed to prometheus-nginxlog-exporter in the field where it is expecting to receive the status code, rather than sending the $status field itself

```
  map $status $status_range {
    "~^(?<range>\d).+" $range;
  }
```

```
log_format exporter '$remote_addr [$time_local] $status_range ...
```
