### ISSUE TITLE
"<namespace>_parse_errors_total" counter and exception for united namespaces

### ISSUE THREAD

**Issue by xzert** [martin-helmich/prometheus-nginxlog-exporter#212]
**Is your feature request related to a problem? Please describe.**
When one of namespaces have errors by some reason (wrong format, not accessible logfile, etc) exporter drop exception like "parse_errors_total was collected previous" (not literally)

**Describe the solution you'd like**
Do conjuction of parse_errors_total metrics in united namespace and increase metric gauge 

**Describe alternatives you've considered**
Maybe add namespace_label for parse_errors_total metric for possible separate broken namespace configs

**Comment by martin-helmich** [comment]
I've added every possible test case I can think of into #218, but they all pass successfully. I'm afraid I'll need an exact configuration example to be able to be able to reproduce this error.

**Comment by xzert** [comment]
Finaly i've got right config for reproduction
