### ISSUE TITLE
Following installation instructions results in permission error

### ISSUE THREAD

**Issue by Foorack** [martin-helmich/prometheus-nginxlog-exporter#225]
**Describe the bug**
Currently when [Installing via DEB](https://github.com/martin-helmich/prometheus-nginxlog-exporter#deb-and-rpm-packages) and simply trying to read from `/var/log/nginx/access.log`, the `CapabilityBoundingSet=` variable in the [systemd service configuration](https://github.com/martin-helmich/prometheus-nginxlog-exporter/blob/b321e09e7e753817e704a1915c181e38f91cf376/res/package/prometheus-nginxlog-exporter.service) currently strips all powers, while on a freshly installed Ubuntu Server 20.04 server the `access.log` file only has `rw-r-----` and is owned by `www-data:adm`, which causes `prometheus-nginxlog-exporter` to crash while "running as root".

There are currently no instructions for the user on how to configure this directly. [Other online tutorials](https://blog.ruanbekker.com/blog/2020/04/25/nginx-metrics-on-prometheus-with-the-nginx-log-exporter/) recommend giving this program unlimited root powers, while miscellaneous StackOverflow threads recommends making all nginx logs world-readable. Steps to proceed from hereon (and maybe add "permission denied" to FAQ) would be greatly appreciated.

**To Reproduce**
Run above-mentioned configuration.

**Expected behavior**
Either clearer instructions telling user how to correctly configure permissions, or an improved error message. Stripping permissions while still running as root can be very confusing to debug.

**Environment**:

- Exporter version: v1.9.1
- OS (e.g. from /etc/os-release): Ubuntu Server 20.04 LTS
- Deployment method (e.g. Docker image, deb/rpm package, self-compiled, ...): DEB
- Others:

**Comment by Foorack** [comment]
Boop

**Comment by Foorack** [comment]
30 days is way too short

**Comment by martin-helmich** [comment]
Apologies. I haven't had time to investigate this in detail, yet. The DEB package has proven itself to be notoriously difficult to maintain for reasons exactly such as these...

Just a few quick thoughts off the top of my head:

1. I would recommend against running the exporter with full root privileges. There are no (known) security vulnerabilities, but I'd nevertheless always recommend adhering to the Principle of Least Privilege as a matter of, well, principle.
2. Changing the log file access mode to world-readable may (or may not) have unintended side effects concerning data privacy, when there are other users on your system that should _not_ have access to that file. Not necessarily (!) a security/privacy vulnerability, but still proceed with caution.
3. Alternatively, when the access.log file is readable by the `adm` group, it might be a possible solution to change the GID of the exporter process to said group. A simple `Group=adm` definition in the `[Service]` section of the systemd unit file might (untested!) just do the trick. You should be able to add this via a systemd drop-in without having to modify the entire unit.

Let me know if any of these are of any help. 🙂

**Comment by Charlymd** [comment]
yes it work !

**Comment by Foorack** [comment]
Hello @martin-helmich

This is not a request to change the security model. Merely to have it more clearly in the documentation.

Right now it is not obvious at all, and I don't think it is mentioned that this "fix"  is required when installing through this method, so it leads to a lot of painful debugging in the beginning.
@Charlymd probably had the same case from their reaction.

**Comment by Astranox** [comment]
As I've also stumbled upon this: Option 3 would be great, and I think also the most correct option (according to https://wiki.debian.org/SystemGroups : "Group adm is used for system monitoring tasks.", which imho seems to be appropriate to be used by a log monitoring tool )
Thanks for building this!

**Comment by olegabr** [comment]
This works just fine:

`$cat /lib/systemd/system/prometheus-nginxlog-exporter.service`

```
[Unit]
Description=NGINX Access Log metrics exporter for Prometheus
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/usr/sbin/prometheus-nginxlog-exporter -config-file /etc/prometheus-nginxlog-exporter.hcl
User=www-data
Group=adm
Type=simple
Restart=on-failure
RestartSec=5s
ProtectSystem=full
CapabilityBoundingSet=

[Install]
WantedBy=multi-user.target

```
