### ISSUE TITLE
Parses IPv4, but not IPv6 client ip addresses

### ISSUE THREAD

**Issue by Haringstad** [martin-helmich/prometheus-nginxlog-exporter#247]
**Describe the bug**
Does parse ipv4 addresses in log, but not the ipv6 client addresses

**To Reproduce**
visiting site by using ipv6 and ipv4 only, provides data of ipv4 visits, but not ipv6 visits.

**Expected behavior**
Both clients should be "read"

**Configuration file** (remove section, if not applicable):

```
namespace "nginx_proxy_staging_api" {
  source = {
    files = [
      "/opt/docker-data/nginx-proxy-manager/data/logs/proxy-host-3_access.log"
    ]
  }
  format = "[$time_local] $upstream_cache_status $upstream_status $status - $request_method $scheme $host \"$request_uri\" [Client $remote_addr] [Length $body_bytes_sent] [Gzip $gzip_ratio] [Sent-to $server] \"$http_user_agent\" \"$http_referer\""

  labels {
    app = "acarat_staging_api"
  }
}


```

**Example log file** (remove section, if not applicable):

```
[17/Mar/2022:16:40:25 +0000] - 200 200 - GET https admin.staging.acarat.nl "/login" [Client 2001:1c04:aaaa:bbbb::1234] [Length 1101] [Gzip -] [Sent-to 172.16.101.54] "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4863.0 Safari/537.36 Edg/100.0.1163.1" "-"

```

**Metrics output** (remove section, if not applicable):

```
nginx_proxy_staging_admin_parse_errors_total 0

```

**Environment**:

- Exporter version: 1.8.0
- OS (e.g. from /etc/os-release): debian 11
- Deployment method (e.g. Docker image, deb/rpm package, self-compiled, ...):  deb
- Others: parsing logs from nginx-proxy-manager

As stated, all IPv4 requests are perfectly seen, and work fine. Only IPv6 clients do not show (metrics that is)

**Comment by martin-helmich** [comment]
Apologies, this should not have gotten stale. IPv6 addresses should be treated just the same as IPv4 addresses (not that the exporter does anything with them, after all 🤷‍♂️). I'll investigate shortly. 🕵️

**Comment by martin-helmich** [comment]
I've tried creating a failing test case from your example files in #254, but failed to reproduce the issue (although, I needed to add a relabel config to populate the `method` label correctly; see below).

Are you certain that this is related to the IP format? Please also take note that the exporter only reads the file from the end, meaning that it will not process lines that are already present in the file when the process starts.

---

On a side note, this is the `relabel` config that I've added to your example to process the `method` label correctly:

```hcl
  relabel "method" {
    from = "request_method"
  }
```
