### ISSUE TITLE
Using the latest commit will panic

### ISSUE THREAD

**Issue by aohan0503** [martin-helmich/prometheus-nginxlog-exporter#262]
**Describe the bug**
panic after running for a few seconds

**To Reproduce**
Package with latest commit

OS: Centos7.6
Go Version: go1.16.5

![image](https://user-images.githubusercontent.com/81146139/168206892-b7f23ab0-a331-4dd1-a034-9156aca20eee.png)

**Comment by martin-helmich** [comment]
Thanks for your report. Can you share a config file with which to reproduce this issue?
