### ISSUE TITLE
Add arm64 binaries/packages

### ISSUE THREAD

**Issue by nantiferov** [martin-helmich/prometheus-nginxlog-exporter#276]
**Is your feature request related to a problem? Please describe.**
Last years ARM architecture became more and more popular in clouds. However, packages for arm64 arch are not available in releases.

**Describe the solution you'd like**
Add arm64 arch to build/release workflows.

**Describe alternatives you've considered**
I can build binary/package by myself locally

**Additional context**
I can try to create a PR with these changes if this ok.

**Comment by nantiferov** [comment]
Not stale, cannot remove label though

**Comment by martin-helmich** [comment]
Sorry this took a while. 😞  From [v1.10.0 onwards](https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/tag/v1.10.0), there'll be both amd64 and arm64 builds. I'll also accept PRs to the `.goreleaser.yml` file for adding additional architectures, if required.
