### ISSUE TITLE
Get data from syslog

### ISSUE THREAD

**Issue by AntonVozdvizhenskiy** [martin-helmich/prometheus-nginxlog-exporter#30]
Hello,
Is it possible to get data from file with syslog format (not changing this format)?

i.e. nginx config:
`log_format nginx2prometheus '$remote_addr [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time $upstream_response_time';`

prometheus-nginxlog-exporter config:
`format = "$remote_addr [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time $upstream_response_time"`

nginx log file:
```
8.8.8.8 [23/Jan/2018:16:00:02 +0300] "GET /bla?id=1 HTTP/1.1" 200 100 "https://bla.com/" "Mozilla/5.0 ..." 0.031 0.031
8.8.8.8 [23/Jan/2018:16:00:03 +0300] "GET /bla?id=2 HTTP/1.1" 200 100 "https://bla.com/" "Mozilla/5.0 ..." 0.032 0.032
```
 
syslog:
```
Jan 23 16:00:02 somehost nginx: 8.8.8.8 [23/Jan/2018:16:00:02 +0300] "GET /bla?id=1 HTTP/1.1" 200 100 "http://bla.com/" "Mozilla/5.0 ..." 0.031 0.031
Jan 23 16:00:03 somehost nginx: 8.8.8.8 [23/Jan/2018:16:00:03 +0300] "GET /bla?id=2 HTTP/1.1" 200 100 "http://bla.com/" "Mozilla/5.0 ..." 0.032 0.032
```

**Comment by martin-helmich** [comment]
Sure. Simply change your `format` in the exporter's config file to match the syslog format (which is essentially the NGINX format with a few prepended fields):

```
format = "$month $day $time $host $service: $remote_addr [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time $upstream_response_time"
```

Hope this helps.

**Comment by AntonVozdvizhenskiy** [comment]
Thanks! it work

**Comment by AntonVozdvizhenskiy** [comment]
Unfortunately, in begining of month it not work  
In syslog date format present leading space, it break regexp parse logic

```
Feb  2 16:00:02 somehost nginx: 8.8.8.8 [23/Jan/2018:16:00:02 +0300] "GET /bla?id=1 HTTP/1.1" 200 100 "http://bla.com/" "Mozilla/5.0 ..." 0.031 0.031
Feb  2 16:00:03 somehost nginx: 8.8.8.8 [23/Jan/2018:16:00:03 +0300] "GET /bla?id=2 HTTP/1.1" 200 100 "http://bla.com/" "Mozilla/5.0 ..." 0.032 0.032
   ^^
```
`format = "$month $day $time $hostname $service: $remote_addr $host [$time_local] \"$request\" $status $body_bytes_sent $request_time $upstream_response_time"`

`^(?P<month>[^ ]*) (?P<day>[^ ]*) (?P<time>[^ ]*) (?P<hostname>[^ ]*) (?P<service>[^:]*): (?P<remote_addr>[^ ]*) (?P<host>[^ ]*) \[(?P<time_local>[^]]*)\] "(?P<request>[^"]*)" (?P<status>[^ ]*) (?P<body_bytes_sent>[^ ]*) (?P<request_time>[^ ]*) (?P<upstream_response_time>[^ ]*)$`
