### ISSUE TITLE
Support upstream

### ISSUE THREAD

**Issue by felixPG** [martin-helmich/prometheus-nginxlog-exporter#31]
> Feature request  
> Support request

Is possible to support upstream metrics for a typical nginx TCP load balancer?

I have a custom log for my load balancer:

log_format basic '$remote_addr - - [$time_local] $protocol $status $bytes_sent $bytes_received $session_time "$upstream_addr"';

Regards

**Comment by martin-helmich** [comment]
For metrics, of all the [`upstream` module's variables](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#variables), only the `$upstream_response_time` is supported at the moment (pull requests are welcome).

For labels, you can use arbitrary upstream variables using the configuration file. For example, to add labels for the `$upstream_addr` and `$upstream_cache_status` variables, you can use the following configuration:

```tf
relabel "upstream_address" {
  from = "upstream_addr"
}

relabel "upstream_cache_status" {
  from = "upstream_cache_status"
}
```

Hope that helps.
