### ISSUE TITLE
RPM package start，Memory continues to grow and never stops

### ISSUE THREAD

**Issue by kkkaiiio** [martin-helmich/prometheus-nginxlog-exporter#326]
**Issue type**:

> Pick one:  
> Feature request  
> Bug report  
> Support request

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Other important information**:

**Configuration file** (remove section, if not applicable):

```hcl
# Please post the contents of your configuration file, here
```

**Metrics output** (remove section, if not applicable):

```
# Please post the output of the exporter's /metrics endpoint, if applicable
```

**Exporter output** (remove section, if not applicable):

```
# Please post the output of the exporter itself, if applicable
```

**Example log file** (remove section, if not applicable):

```
# Please post an excerpt of a log file that can be used to reproduce the error
# Keep the excerpt as short as possible and make sure to redact any sensitive data.
```

**Environment**:
- Exporter version:
- OS (e.g. from /etc/os-release):
- Others:

**Comment by shsteve** [comment]
I had encountered a similar problem also, have this problem been solved?
