### ISSUE TITLE
how to use this module ?

### ISSUE THREAD

**Issue by bsushant-athena** [martin-helmich/prometheus-nginxlog-exporter#33]
**Issue type**:

> Support request

**What happened**:
I have nginx running in a container. I want to use this use this module , I tried this below command:
docker run --name nginx-exporter -p 4040:4040 -v logs:/mnt/nginxlogs -v /Users/bsushant/gateway/docker/nginx-log-exporter/prometheus-nginxlog-exporter.yml:/etc/prometheus-nginxlog-exporter.yml quay.io/martinhelmich/prometheus-nginxlog-exporter -config-file /etc/prometheus-nginxlog-exporter.yml

**How to reproduce it (as minimally and precisely as possible)**:
My config file is>>
http://jsoneditoronline.org/?id=aaa0390449aa2b11b87fa0d13171c32e

**Metrics output** (remove section, if not applicable):

```
loading configuration file /etc/prometheus-nginxlog-exporter.yml
illegal
illegal
panic: At 2:7: illegal char

goroutine 1 [running]:
main.main()
	/go/src/github.com/martin-helmich/prometheus-nginxlog-exporter/main.go:125 +0xcc2
```

**Environment**: local
- Exporter version: latest image
- OS (e.g. from /etc/os-release): mac
- Others: docker 1.17.0

**Comment by martin-helmich** [comment]
Ouch. Support for YAML configuration files has been merged, but not yet been included in a release. Sorry for the confusion.

Releasing a new tag 1.2.0 now; the container image should be available within a few minutes.

**Comment by bsushant-athena** [comment]
Also if you could tell how to run this module inside nginx container?

**Comment by martin-helmich** [comment]
This is not an NGINX module. It's a separate process designed to run in a separate container. I'd recommend having your NGINX container write its logs into a data volume which can be shared with the exporter container.

If you _really_ want the exporter and NGINX to run in the same container _anyways_, you'll need to build your own image on top of an NGINX base image, add the exporter binary and [use a process manager like supervisord](https://docs.docker.com/config/containers/multi-service_container/) to start both NGINX and the exporter within the same container.

**Comment by bsushant-athena** [comment]
Can you share path for the exporter binary ?  @martin-helmich

**Comment by bsushant-athena** [comment]
@martin-helmich  can you share the path to get the exporter binary file ?

**Comment by martin-helmich** [comment]
Have a look at the project's "releases" page
