### ISSUE TITLE
404 error at startup

### ISSUE THREAD

**Issue by Thecrafterja** [martin-helmich/prometheus-nginxlog-exporter#338]
**Describe the bug**
When I start this exporter (new installation), it crashes because of an error, probably related to the connection with Prometheus. I use a new install of Prometheus (Docker Hub image: prom/prometheus).

I have double checked, that this problems are not caused by my firewall. I also tried the request the exporter does myself with Postman, but it also got an 404 error code.

**To Reproduce**
1. Setup a new Prometheus instance through the Docker image named above.
2. Setup and configure a new instance of this exporter (with docker).
3. Run the exporter.

**Expected behavior**
Exporter connects to Prometheus.

**Configuration file**

```
listen {
  port = 4040
  address = "192.168.178.201"
  metrics_endpoint = "/metrics"
}

consul {
  enable = true
  address = "192.168.178.211:9090"
  datacenter = "dc1"
  scheme = "http"
  token = ""
  service {
    id = "nginx-exporter"
    name = "nginx-exporter"
    address = "192.168.178.211"
    tags = ["foo", "bar"]
  }
}

namespace "vaultwarden" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
  source {
    files = [
      "/var/log/nginx/*_access.log"
    ]
  }

  # log can be printed to std out, e.g. for debugging purposes (disabled by default)
  print_log = true

  # metrics_override = { prefix = "myprefix" }
  # namespace_label = "vhost"

  labels {
    app = "application-one"
    environment = "production"
    foo = "bar"
  }

  histogram_buckets = [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
}
```

**Exporter log**

```
2023-08-02T13:07:31.650Z        info    prometheus-nginxlog-exporter/main.go:162        loading configuration file /etc/prometheus-nginxlog-exporter.hcl
2023-08-02T13:07:31.650Z        info    config/struct_namespace.go:95   Resolved globs /var/log/nginx/*_access.log to []
2023-08-02T13:07:31.650Z        info    prometheus-nginxlog-exporter/main.go:182        registering service in Consul[]
2023-08-02T13:07:31.653Z        fatal   prometheus-nginxlog-exporter/main.go:184        Unexpected response code: 404 (404 page not found)
main.setupConsul
        /home/runner/work/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter/main.go:184
main.main
        /home/runner/work/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter/main.go:130
runtime.main
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250
```

**Environment**:

- Exporter version: latest on quay.io (v1.11)
- OS (e.g. from /etc/os-release): Ubuntu 22.04.2 LTS
- Deployment method (e.g. Docker image, deb/rpm package, self-compiled, ...): Docker
- Prometheus image: prom/prometheus

I would really appreciate some feedback ;).

**Comment by martin-helmich** [comment]
This seems to be a general misunderstanding:

The exporter does not need to "connect to Prometheus"; instead, you need to configure Prometheus to connect to the exporter.

The process crashes because it attempts to connect to Consul, but fails. I assume that the `192.168.178.211:9090` in your configuration file is actually a Prometheus endpoint, and not Consul?

Suggestion: If you do not use Consul, drop the Consul configuration.
