### ISSUE TITLE
Metrics persistence

### ISSUE THREAD

**Issue by voidking** [martin-helmich/prometheus-nginxlog-exporter#343]
**Is your feature request related to a problem? Please describe.**
When the exporter is restarted, all monitoring metrics will be reset.
At this time, the data obtained by prometheus will fall off a cliff, which is very unreasonable.

**Describe the solution you'd like**
Persist every once in a while (for example, every 10s), and read data from the persistent data when the exporter is restarted.

**Comment by stempler** [comment]
With what kind of metrics do you see that as a problem? I think that is the normal behavior for Prometheus metrics in general and Prometheus is ready to deal with that.

For example for counter metrics, it is normal that they may reset also without restart (they can't grow infinitely after all). Functions like `rate` and `increase` should be used to process counters, looking at the change in a certain time, and they are able to deal with counter resets.

**Comment by voidking** [comment]
Thanks for your reply. 
`Rate` and `increase` are generally not greatly affected, but `counter` will be greatly affected. 
For example, if I want to count the total number of visits in the last hour, day or week, if a reset occurs during this period, then I may get a negative number result.
To be more specific, assuming that the value of `nginx_http_response_count_total` was 10000 a day ago, and the exporter restarted today, and the value is 1 at this time, then the number of visits I get is -9999.

**Comment by voidking** [comment]
> Not sure what you want to track here - it should be no problem using `increase` to for instance get daily request counts (or for some other time frame where metrics are retained).
> 
> If you want to have a counter of requests over a time that extends what is stored in Prometheus, then I think Prometheus might not be the right tool or you would at least need to process and store the information somewhere else.

Thank u. I made a mistake. When calculating the number of visits over a period of time, it is not simply subtracting, but using functions such as `increase` and `rate`.
