### ISSUE TITLE
binding to TCP6 PORTS?

### ISSUE THREAD

**Issue by Adel-Magebinary** [martin-helmich/prometheus-nginxlog-exporter#36]
root@5f2be741-a708-4ed3-dcd8-e1d43aface6a:~# netstat -an | grep 5050
tcp6       0      0 :::5050                 :::*                    LISTEN

**Comment by martin-helmich** [comment]
Sorry, but I'm going to need a bit more information, here. What's the exact issue?

By default, the exporter will listen on all interfaces, both IPv4 and IPv6. Counter-intuitively, this will also happen when `0.0.0.0` is specified as listen address -- see golang/go#17615 for more information.

**Comment by Adel-Magebinary** [comment]
Hello Martin,

This is all good. It's partly my fault. It's all sorted now.
