### ISSUE TITLE
Convert invalid namespaces values automatically

### ISSUE THREAD

**Issue by martin-helmich** [martin-helmich/prometheus-nginxlog-exporter#39]
Follow-up on an idea provided by @jorinvo in #37:

>In my case I would like it the most if dashes are converted to underscores since that would save be word in pre-formatting the string in Ansible.

**Comment by jorinvo** [comment]
I still think that this should probably not be enabled by default, but could be interesting as addition when enabling via a flag.
When fixing dashes, would also need to think about other invalid characters and how to handle them. Some characters are best deleted others have reasonable replacement values. It's hard to do this right I am afraid..

**Comment by martin-helmich** [comment]
True, this still needs to be given some thought. I just opened this issue so the suggestion does not get lost after closing #37.
