### ISSUE TITLE
support export $request_path

### ISSUE THREAD

**Issue by micln** [martin-helmich/prometheus-nginxlog-exporter#392]
**Describe the bug**
I use the default log format
$request is `"GET /xxx HTTP/1.1"`
but the metric result got only "GET" but not "/xxx"
is it has some options to suport it ?
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/0879a7ec-e45c-4a10-b001-a258b9a440f0">

**Configuration file** (remove section, if not applicable):

```
    format: "$_ $host nginx: $http_x_forwarded_for - $remote_user [$time_local] \"$request\" \"$request_body\" $status $request_time $upstream_response_time $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
```

**Example log file** (remove section, if not applicable):

```
2024-01-01 host_name_XXX nginx: - - - [time] "GET /metrics HTTP/1.1" "-" 200 0.545 0.545 70 "-" "xxx"
```

**Metrics output** (remove section, if not applicable):

```
nginx_test_http_upstream_time_seconds_hist_bucket{app="nginx_test",environment="testing",method="GET",status="200",le="0.1"} 
```

**Comment by micln** [comment]
I got it, thanks

**Comment by alonwillmakeit** [comment]
@micln hey , would you mind sharing how did you solve it ?
