### ISSUE TITLE
s3 support

### ISSUE THREAD

**Issue by hbceylan** [martin-helmich/prometheus-nginxlog-exporter#42]
**Issue type**:
Feature request 

Do you have any plan for s3 support?

Thanks,

**Comment by martin-helmich** [comment]
No immediate plans. Reading from S3 might prove difficult as the exporter is pretty much reliant on reading access log data from a continuous data stream. What are your thoughts on how exactly an S3 integration would look like?

**Comment by martin-helmich** [comment]
Closed for lack of feedback.
