### ISSUE TITLE
Log waiting to listen access log

### ISSUE THREAD

**Issue by bhagujava** [martin-helmich/prometheus-nginxlog-exporter#51]
**Bug Report**:

> Bug report  

**What happened**:
The exporter doesn't not exporting log.

**Other important information**:

using configuration {{%!s(int=4040) 0.0.0.0} {%!s(bool=false)     {  []}} [{nginx [/home/bhargavpatel/sourceinstallation/nginx/nginx/logs/access.log] $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" map[] [] [] []}] %!s(bool=false)}
starting listener for namespace nginx
running HTTP server on address 0.0.0.0:4040
2018/11/01 08:46:43 Waiting for /home/bhargavpatel/sourceinstallation/nginx/nginx/logs/access.log to appear...

**Configuration file** :

```
listen {
  port = 4040
}

consul {
  enable = true
  address = "localhost:8500"
  datacenter = "dc1"
  scheme = "http"
  token = ""
  service {
    id = "nginx-exporter"
    name = "nginx-exporter"
    tags = ["foo", "bar"]
  }
}

namespace "nginx" {
  source_files = [
    "test.log",
    "foo.log"
  ]
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""

  labels {
    app = "magicapp"
    foo = "bar"
  }

  relabel "user" {
    from = "remote_user"
    // whitelist = ["-", "user1", "user2"]
  }

  relabel "request_uri" {
    from = "request"
    split = 2

    match "^users/[0-9]+" {
      replacement = "/users/:id"
    }
  }
}
    
````
**Environment**:
- Exporter version: latest
- OS : ubuntu 18.04 lts
- Others: 
nginx version: 1.10.1 (installed from source)

**Comment by martin-helmich** [comment]
Difficult to debug without additional information.

- What user does your exporter run as? Is that user authorized to read files from your user's home directory?
- How did your start the exporter? Systemd unit or simply from a command-line?

**Comment by martin-helmich** [comment]
Closed for lack of feedback. Feel free to reopen.
