### ISSUE TITLE
Flexible log_format

### ISSUE THREAD

**Issue by emeriss** [martin-helmich/prometheus-nginxlog-exporter#56]
We use this log_format : 

"$hostname \"$remote_addr\" - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" \"$geoip_city_country_code\" \"$http_cf_ray\" \"$uuid\"

How can I implement this in the xporter without altering code?

**Comment by martin-helmich** [comment]
I don't get the problem. You can specify the log format in the configuration file. Any specific error that you've encountered?

**Comment by martin-helmich** [comment]
Closed for lack of feedback. Feel free to reopen.
