### ISSUE TITLE
Two and more upstream servers

### ISSUE THREAD

**Issue by patsevanton** [martin-helmich/prometheus-nginxlog-exporter#60]
**Issue type**:

> Support request

**What happened**:
urt="0.005 : 0.019"' does not match given format '^(?P<remote_addr>[^ ]*)
May be prometheus-nginxlog-exporter dont support two upstream servers

**What you expected to happen**:
get last prometheus-nginxlog-exporter.
Use log_format from site.

**How to reproduce it (as minimally and precisely as possible)**:

**Other important information**:

**Configuration file** (remove section, if not applicable):

```hcl
listen {
  port = 4040
  address = "10.2.53.52"
}

namespace "app1" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
  source_files = [
    "/var/log/nginx/app-access.log"
  ]
  labels {
    app = "application-one"
    environment = "production"
    foo = "bar"
  }
}
```

**Metrics output** (remove section, if not applicable):

```
# Please post the output of the exporter's /metrics endpoint, if applicable
```

**Exporter output** (remove section, if not applicable):

```
# Please post the output of the exporter itself, if applicable
```

**Example log file** (remove section, if not applicable):
error while parsing line '10.193.84.23 - - [11/Mar/2019:19:58:33 +0300] "GET /offsets.... HTTP/1.1" 200 151 "-" "Java/1.8.0_144"rt=0.024 uct="0.001 : 0.001" uht="0.005 : 0.019" urt="0.005 : 0.019"': access log line '10.193.84.23 - - [11/Mar/2019:19:58:33 +0300] "GET /offsets... HTTP/1.1" 200 151 "-" "Java/1.8.0_144"rt=0.024 uct="0.001 : 0.001" uht="0.005 : 0.019" urt="0.005 : 0.019"' does not match given format '^(?P<remote_addr>[^ ]*) - (?P<remote_user>[^ ]*) \[(?P<time_local>[^]]*)\] "(?P<request>[^"]*)" (?P<status>[^ ]*) (?P<body_bytes_sent>[^ ]*) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)" "(?P<http_x_forwarded_for>[^"]*)"'

```
# Please post an excerpt of a log file that can be used to reproduce the error
# Keep the excerpt as short as possible and make sure to redact any sensitive data.
```

**Environment**:
- Exporter version:
1.2.1
- OS (e.g. from /etc/os-release):
cat /etc/redhat-release 
CentOS release 6.7 (Final)

- Others:

**Comment by martin-helmich** [comment]
>May be prometheus-nginxlog-exporter dont support two upstream servers
Nothing so complicated, from the looks of it. You actual access log format does not match the format configured in your config file.

**Comment by martin-helmich** [comment]
Closing for now. Feel free to reopen if needed.
