### ISSUE TITLE
Increase Histogram buckets above 10 seconds

### ISSUE THREAD

**Issue by MPV** [martin-helmich/prometheus-nginxlog-exporter#64]
**Issue type**: Feature request  

Would you be open to increasing the upper limit of the histogram buckets?

**What happened**:

When I have response times over 10 seconds, my graphs are "cut off" above the 10s mark:

![Skärmklipp 2019-05-03 09 39 23](https://user-images.githubusercontent.com/62675/57125255-0bf40780-6d89-11e9-87ca-634ce5f27ed4.png)

This is probably because of the default buckets in the Histogram metrics having an upper bound of 10 seconds.

**What you expected to happen**:

Either:

a) Higher upper limit bucket so we can measure slower responses than 10s.

b) Ability to configure my own buckets for the histograms.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have many responses being slower than 10s.
2. Graph them using histogram quantiles:

`histogram_quantile(0.9999, sum(rate(http_response_time_seconds_hist_bucket[10m])) by (le))`

**Metrics output** (remove section, if not applicable):

```
[...]
# HELP http_response_time_seconds_hist Time needed by NGINX to handle requests
# TYPE http_response_time_seconds_hist histogram
http_response_time_seconds_hist_bucket{method="GET",status="200",le="0.005"} 514876
http_response_time_seconds_hist_bucket{method="GET",status="200",le="0.01"} 1.042195e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="0.025"} 1.864966e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="0.05"} 2.18366e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="0.1"} 2.263013e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="0.25"} 2.674159e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="0.5"} 2.803495e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="1"} 2.946707e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="2.5"} 3.080668e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="5"} 3.137246e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="10"} 3.160643e+06
http_response_time_seconds_hist_bucket{method="GET",status="200",le="+Inf"} 3.173146e+06
http_response_time_seconds_hist_sum{method="GET",status="200"} 1.0411615320055158e+06
http_response_time_seconds_hist_count{method="GET",status="200"} 3.173146e+063.173138e+06
[...]
```

**Environment**:
- Exporter version: 1.2.1

**Other important information**:

This seems to be how to change the buckets (by passing custom `Buckets []float64` to the HistogramOpts):
https://godoc.org/github.com/prometheus/client_golang/prometheus#HistogramOpts

```
DefBuckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}
```

👆 ...and these seem to be the default buckets:
https://godoc.org/github.com/prometheus/client_golang/prometheus#pkg-variables

This is where in the code I imagine it could be set:
https://github.com/martin-helmich/prometheus-nginxlog-exporter/blob/v1.2.1/main.go#L91-L95

**Comment by martin-helmich** [comment]
Sure thing, shouldn't be too complicated. I'd probably solve this by adding a configuration parameter so that the buckets can be configured using the configuration file.
