### ISSUE TITLE
Want to add one more /handler  in metrics. Please help to me do that ..

### ISSUE THREAD

**Issue by manukoli1986** [martin-helmich/prometheus-nginxlog-exporter#66]
**Issue type**:

> Pick one:  
> Feature request  
> Bug report  
> Support request

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Other important information**:

**Configuration file** (remove section, if not applicable):

```hcl
# Please post the contents of your configuration file, here
```

**Metrics output** (remove section, if not applicable):

```
# Please post the output of the exporter's /metrics endpoint, if applicable
```

**Exporter output** (remove section, if not applicable):

```
# Please post the output of the exporter itself, if applicable
```

**Example log file** (remove section, if not applicable):

```
# Please post an excerpt of a log file that can be used to reproduce the error
# Keep the excerpt as short as possible and make sure to redact any sensitive data.
```

**Environment**:
- Exporter version:
- OS (e.g. from /etc/os-release):
- Others:

**Comment by martin-helmich** [comment]
I don't really get what you're trying to do. Can you clarify a bit?

**Comment by martin-helmich** [comment]
Closed due to lack of feedback. Feel free to re-open.
