### ISSUE TITLE
Can I scrap logs from nginx docker stdout, from a docker swarm ?

### ISSUE THREAD

**Issue by rjshrjndrn** [martin-helmich/prometheus-nginxlog-exporter#67]
**Issue type**:

> Support request

Can this tool scrape metrics from docker containers, which will stdout logs. 
I've 4 nginx containers running in a docker swarm,.

**Environment**:

- OS (e.g. from /etc/os-release): ubuntu 16.04 with docker swarm

**Comment by martin-helmich** [comment]
Not currently. Given that this request has received some ❤️'s by now, I'll try and see if I can get this implemented.

**Comment by stempler** [comment]
An alternative approach is including nginx and the exporter in the same image and then directly scrape from the nginx container. I did this experimentally [here](https://github.com/wetransform-os/docker-nginx-metrics). Probably not a best practice but may be handy in some situations. There is likely a lot of potential for improvement in the simple wrapper script I used.

**Comment by leobasilio** [comment]
Just documenting another approach. I handled that using the host as a "bridge". When running nginx's container I used `-v /host/path/access.log:/var/log/access.log` and on nginxlog's I used `-v /host/path/access.log:/mnt/access.log:ro`. It works perfectly.

**Comment by cb3inco** [comment]
I did something similar to @leobasilio - I handle my nginx logs to a volume for nginx,

volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/conf.d:/etc/nginx/conf.d
          - ./nginx/certs:/etc/nginx/certs
          - ./nginx/logs:/var/log/nginx/

then in my nginxlog exporter config in my docker-compose I mapped that volume paths as follows:

volumes:
          - ./nginx/logs:/var/log/nginx
          - ./nginxlogs:/etc/

All is working now.
