### ISSUE TITLE
log specific json format

### ISSUE THREAD

**Issue by k-manolis** [martin-helmich/prometheus-nginxlog-exporter#68]
I have a nginx server writing logs with this specific format:
```sh
log_format  access_log_json escape=json '{'
 "name"         : "$name",'
 "hostname"  : "$hostname",'
 "endpoint"   : "$endpoint",'
 '}';
```
I want to parse the above format to the hcl configuration.
I have made a lot of tries.  
The last one :
```hcl
 format {
    "name"        = "$name",
    "hostname"  = "$hostname",
    "endpoint"   = "$endpoint",
   }
```
I am getting this error :  
```sh
panic: At 8:7: root.namespace[0].format: unknown type for string *ast.ObjectList
```
I am running on CENTOS 7 

Could you please help me with the above issue ?

**Comment by martin-helmich** [comment]
Your supplied configuration is not syntactically valid HCL. Also, `format` needs to be a string. Currently, the exporter uses regular expressions (or more precisely, a format string that is then converted to a regular expression) for parsing log lines, which makes it inherently unsuitable for parsing JSON output.

You could try having your NGINX server write a second log file in a regex-parseable format.
