### ISSUE TITLE
unrecognized import path "golang.org/x/sys" 

### ISSUE THREAD

**Issue by songlaibin** [martin-helmich/prometheus-nginxlog-exporter#72]
**Issue type**:

> Pick one:  
> Feature request  
> Bug report  
> Support request

**What happened**:
Thank you very much for this very useful exporter. When I compiled the arm platform, a Ge package expired and could not be downloaded. Is there an alternative?

go: golang.org/x/sys@v0.0.0-20161023150541-c200b10b5d5e: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or esta
blished connection failed because connected host has failed to respond.)
go: error loading module requirements
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Other important information**:

**Configuration file** (remove section, if not applicable):

```hcl
# Please post the contents of your configuration file, here
```

**Metrics output** (remove section, if not applicable):

```
# Please post the output of the exporter's /metrics endpoint, if applicable
```

**Exporter output** (remove section, if not applicable):

```
# Please post the output of the exporter itself, if applicable
```

**Example log file** (remove section, if not applicable):

```
# Please post an excerpt of a log file that can be used to reproduce the error
# Keep the excerpt as short as possible and make sure to redact any sensitive data.
```

**Environment**:
- Exporter version:
- OS (e.g. from /etc/os-release):
- Others:

**Comment by martin-helmich** [comment]
This doesn't look like an issue with the exporter, but rather with your network connection. Looks like either `golang.org` or `go.googlesource.com` was not reachable from your build machine.

**Comment by songlaibin** [comment]
Thank you for your reply. It's really not a problem. It's really the reason for my network. It has been solved. Thank you very much.
