### ISSUE TITLE
running prometheus-nginxlog-exporter.service

### ISSUE THREAD

**Issue by k-r-a** [martin-helmich/prometheus-nginxlog-exporter#8]
First of all, I am sorry that I am asking this question as an "issue" as I could not find any other way to contact you.

I am new to Go, prometheus and exporters. I am trying to use this exporter to collect metrics from nginx server for prometheus.

In your README.md under "Running the collector", you have specified that "The shipped unit file expects the binary to be located in /usr/local/bin/prometheus-nginxlog-exporter". My binary file is  /root/projects/bin/prometheus-nginxlog-exporter

I have followed the steps below:
1) Installed Go on nginx server
2) $GOPATH is /root/projects
3) # git clone https://github.com/martin-helmich/prometheus-nginxlog-exporter.git $GOPATH/src/github.com/martin-helmich/prometheus-nginxlog-exporter
4)#  cd $GOPATH/src/github.com/martin-helmich/prometheus-nginxlog-exporter
5)# go install
6) This created a binary in $GOPATH/bin with the name "prometheus-nginxlog-exporter"
7) Contents of my /etc/prometheus-nginxlog-exporter.hcl file are as below:

 `listen {
  port = 4040
  address = "localhost"
}

consul {
  enable = true
  address = "localhost:8500"
  service {
    id = "nginx-exporter"
    name = "nginx-exporter"
    datacenter = "dc1"
    scheme = "http"
    token = ""
    tags = ["foo", "bar"]
  }
}

namespace "somehostname" {
  source_files = [
    "/var/log/nginx/access.log",
    "/var/log/nginx/error.log"
  ]
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $cookie_session"
  labels {
    app = "rtiproxy3"
    foo = "bar"
  }
}`

8) Then I took the unit file from git
 # wget -O /etc/systemd/system/prometheus-nginxlog-exporter.service https://raw.githubusercontent.com/martin-helmich/prometheus-nginxlog-exporter/master/systemd/prometheus-nginxlog-exporter.service 

9) Modified /etc/systemd/system/prometheus-nginxlog-exporter.service to have the below contents:

`[Unit]
Description=NGINX metrics exporter for Prometheus
After=network-online.target

[Service]
ExecStart=/root/projects/bin/prometheus-nginxlog-exporter -config-file /etc/prometheus-nginxlog-exporter.hcl
Restart=always
ProtectSystem=full
CapabilityBoundingSet=

[Install]
WantedBy=multi-user.target
`

10)# systemctl enable prometheus-nginxlog-exporter
11)# systemctl start prometheus-nginxlog-exporter
12)# service prometheus-nginxlog-exporter status - gives me the following error

`prometheus-nginxlog-exporter.service - NGINX metrics exporter for Prometheus
   Loaded: loaded (/etc/systemd/system/prometheus-nginxlog-exporter.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2017-04-25 17:05:50 BST; 11s ago
  Process: 59938 ExecStart=/root/projects/bin/prometheus-nginxlog-exporter -config-file /etc/prometheus-nginxlog-exporter.hcl (code=exited, status=2)
 Main PID: 59938 (code=exited, status=2)

Apr 25 17:05:50 somehostname.net systemd[1]: Unit prometheus-nginxlog-exporter.service entered failed state.
Apr 25 17:05:50 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service failed.
Apr 25 17:05:50 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service holdoff time over, scheduling restart.
Apr 25 17:05:50 somehostname.net systemd[1]: start request repeated too quickly for prometheus-nginxlog-exporter.service
Apr 25 17:05:50 somehostname.net systemd[1]: Failed to start NGINX metrics exporter for Prometheus.
Apr 25 17:05:50 somehostname.net systemd[1]: Unit prometheus-nginxlog-exporter.service entered failed state.
Apr 25 17:05:50 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service failed.`

13) There seems to be an issue with the binary that I created. Please could you let me know what is the issue.

Many Thanks!
@k-r-a

**Comment by martin-helmich** [comment]
In general, I would suggest using the latest pre-built version from the [releases page](https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases). That way, you'll get a stable release, instead of the (potentially unstable) master branch and won't have to build the binary yourself.

Regarding the systemd unit file; please have a look at the output of `journalctl -u prometheus-nginxlog-exporter` and post it here, if the error message within is unclear.

**Comment by k-r-a** [comment]
Hi Martin,
Thanks for your reply. I have used the binary from releases as you suggested and tried to run it again, but it failed again with the error : prometheus-nginxlog-exporter.service: main process exited, code=exited, status=2/INVALIDARGUMENT


Following is the trace for journalctl -u prometheus-nginxlog-exporter

-- Logs begin at Thu 2017-04-27 07:10:50 BST, end at Thu 2017-04-27 10:53:03 BST. --
Apr 27 07:11:12 somehostname.net systemd[1]: Started NGINX metrics exporter for Prometheus.
Apr 27 07:11:12 somehostname.net systemd[1]: Starting NGINX metrics exporter for Prometheus...
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: loading configuration file /etc/prometheus-nginxlog-exporter.hcl
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: &{{4040 localhost} {true localhost:8500    {nginx-exporter nginx-exporter [foo bar]}} [{somehostname [/
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: using configuration {{%!s(int=4040) localhost} {%!s(bool=true) localhost:8500    {nginx-exporter ngi
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: registering service in Consul
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: panic: Put http://localhost:8500/v1/agent/service/register?dc=dc1: dial tcp [::1]:8500: getsockopt: 
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: goroutine 1 [running]:
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: panic(0x6fbe60, 0xc4200dd230)
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: main.main()
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1070]: /root/projects/src/github.com/martin-helmich/prometheus-nginxlog-exporter/main.go:115 +0x9c1
Apr 27 07:11:13 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 27 07:11:13 somehostname.net systemd[1]: Unit prometheus-nginxlog-exporter.service entered failed state.
Apr 27 07:11:13 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service failed.
Apr 27 07:11:13 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service holdoff time over, scheduling restart.
Apr 27 07:11:13 somehostname.net systemd[1]: Started NGINX metrics exporter for Prometheus.
Apr 27 07:11:13 somehostname.net systemd[1]: Starting NGINX metrics exporter for Prometheus...
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: loading configuration file /etc/prometheus-nginxlog-exporter.hcl
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: &{{4040 localhost} {true localhost:8500    {nginx-exporter nginx-exporter [foo bar]}} [{somehostname [/
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: using configuration {{%!s(int=4040) localhost} {%!s(bool=true) localhost:8500    {nginx-exporter ngi
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: registering service in Consul
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: panic: Put http://localhost:8500/v1/agent/service/register?dc=dc1: dial tcp [::1]:8500: getsockopt: 
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: goroutine 1 [running]:
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: panic(0x6fbe60, 0xc42000ccf0)
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: main.main()
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: /root/projects/src/github.com/martin-helmich/prometheus-nginxlog-exporter/main.go:115 +0x9c1
Apr 27 07:11:13 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 27 07:11:13 somehostname.net systemd[1]: Unit prometheus-nginxlog-exporter.service entered failed state.
Apr 27 07:11:13 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service failed.
Apr 27 07:11:13 somehostname.net systemd[1]: prometheus-nginxlog-exporter.service holdoff time over, scheduling restart.
Apr 27 07:11:13 somehostname.net systemd[1]: Started NGINX metrics exporter for Prometheus.
Apr 27 07:11:13 somehostname.net systemd[1]: Starting NGINX metrics exporter for Prometheus...
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: loading configuration file /etc/prometheus-nginxlog-exporter.hcl
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: &{{4040 localhost} {true localhost:8500    {nginx-exporter nginx-exporter [foo bar]}} [{somehostname [/
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: using configuration {{%!s(int=4040) localhost} {%!s(bool=true) localhost:8500    {nginx-exporter ngi
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: registering service in Consul
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: panic: Put http://localhost:8500/v1/agent/service/register?dc=dc1: dial tcp [::1]:8500: getsockopt: 
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: goroutine 1 [running]:
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: panic(0x6fbe60, 0xc420104cc0)
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1842]: main.main()

**Comment by martin-helmich** [comment]
>Apr 27 07:11:13 somehostname.net prometheus-nginxlog-exporter[1735]: panic: Put http://localhost:8500/v1/agent/service/register?dc=dc1: dial tcp [::1]:8500: getsockopt:

This. You've set `consul.enable = true` in your configuration file but do not appear to have a Consul server listening on `localhost:8500`. Either disable the Consul integration in your configuration file or ensure that a Consul server is running on the configured URL.

**Comment by k-r-a** [comment]
I have disabled consul and it works now.
Thanks !
