### ISSUE TITLE
[Question] How can I grab mertics for response time and other?

### ISSUE THREAD

**Issue by Sudokamikaze** [martin-helmich/prometheus-nginxlog-exporter#84]
**Issue type**:
> Support request

**What happened**:
Your project readme says: `Keep in mind that some of these metrics will require certain values to be present in your access log format `

And this line confuses: `The exporter exports the <namespace>_http_response_count_total metric, but not [other metric that is mentioned in the README]!`

**What you expected to happen**:
I expected logic behavior, as I've defined proper variables, I don't see any of them on /metrics paje

**How to reproduce it (as minimally and precisely as possible)**:
NGINX conf:
```
log_format upstream_time '$remote_addr - [$time_local] '
                         '"$request" $status $body_bytes_sent '
                         '"$http_referer" "$http_user_agent" '
                         'rt="$request_time" uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
```

Exporter's conf:
```
    format = "$remote_addr - [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $upstream_response_time"
```

**Other important information**:

**Configuration file** (remove section, if not applicable):

```hcl
# Please post the contents of your configuration file, here
```

**Metrics output** (remove section, if not applicable):

```
# Please post the output of the exporter's /metrics endpoint, if applicable
```

**Exporter output** (remove section, if not applicable):
```
Oct 19 15:52:06 proxy-com prometheus-nginxlog-exporter[27893]: loading configuration file /etc/prometheus-nginxlog-exporter.hcl
Oct 19 15:52:06 proxy-com prometheus-nginxlog-exporter[27893]: using configuration {Listen:{Port:4040 Address:0.0.0.0} Consul:{Enable:false Address: 
Oct 19 15:52:06 proxy-com prometheus-nginxlog-exporter[27893]: starting listener for namespace nginx
Oct 19 15:52:06 proxy-com prometheus-nginxlog-exporter[27893]: running HTTP server on address 0.0.0.0:4040
Oct 19 15:52:06 proxy-com prometheus-nginxlog-exporter[27893]: 2019/10/19 15:52:06 Seeked /var/log/nginx/access.log - &{Offset:0 Whence:2}
```
```
# Please post the output of the exporter itself, if applicable
```

**Example log file** (remove section, if not applicable):
```
1.1.1.1 - [19/Oct/2019:15:56:55 +0300] "POST /ru/ HTTP/1.1" 200 64 "URL_REQUESTED" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1" rt="4.711" uct="0.001" uht="4.699" urt="4.699"
```
```
# Please post an excerpt of a log file that can be used to reproduce the error
# Keep the excerpt as short as possible and make sure to redact any sensitive data.
```

**Environment**:
- Exporter version: Latest from GH releases
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Others:

**Comment by martin-helmich** [comment]
Apparently, your Nginx has a different log format configured in its config file than the exporter. They need to match.

**Comment by Sudokamikaze** [comment]
> Apparently, your Nginx has a different log format configured in its config file than the exporter. They need to match.

Hey, thanks for replying me! I've tried following `log_format` configuration:
```
log_format upstream_time '$remote_addr - [$time_local] '
                         '"$request" $status $body_bytes_sent '
                         '"$http_referer" "$http_user_agent" '
                         '"$request_time" "$upstream_connect_time" "$upstream_header_time" "$upstream_response_time"';
```

**Comment by martin-helmich** [comment]
Hey. In your previous configuration, the two log formats didn't match either (referring, for example, to the quotes around `$request_time` and the other variables, that are present in your NGINX config, but not in the exporter config).
