### ISSUE TITLE
Not getting http response metrics

### ISSUE THREAD

**Issue by arulvelu21** [martin-helmich/prometheus-nginxlog-exporter#9]
Hi Martin ,

I have been using nginx exporter module to collect metrics such as https requests and http response metrics count .  Have referred this blog to perform the same "https://www.martin-helmich.de/en/blog/monitoring-nginx.html"

Currently in dropdown i am getting metrics only related to http requests metrics .I have changed my nginx log format as shown below :

'$remote_addr - $remote_user [$time_local] ''"$request" $status $body_bytes_sent ''"$http_referer" "$http_user_agent" ''$request_time $upstream_response_time $pipe';

However i dont see any metrics related to http response . Please assist me .

**Comment by martin-helmich** [comment]
Sorry for the late response. In case this is still current, a few debugging hints:

- Check if the metrics are exported correctly. To do this, you can try to request the exporter's `/metrics` endpoint by yourself, for example by `curl`'ing http://localhost:4040/metrics.
- Check if the exporter is correctly configured as a target in Prometheus (use the _Targets_ menu item for this). Refer to [the documentation](https://prometheus.io/docs/operating/configuration/#<scrape_config>) if necessary.

**Comment by martin-helmich** [comment]
Closing. Feel free to re-open in case this is still current.
