### ISSUE TITLE
error while parsing line 

### ISSUE THREAD

**Issue by 15astro** [martin-helmich/prometheus-nginxlog-exporter#91]
**Issue type**: Bug report  

**What happened**: Failing to parse nginx logs

**What you expected to happen**: Parse nginx logs based on the given format

**How to reproduce it (as minimally and precisely as possible)**: Run exporter against nginx-logs generator using this tool: https://github.com/liubin/nginx-log-generator

**Other important information**: 
Format specified: `"$remote_addr -  $remote_user    [$time_local]                \"$request\"                     $status  $body_bytes_sent  \"$http_referer\"         \"$http_user_agent\"                                        $process_time $bytes_sent $request_length"`

Sample log line: `28.90.74.145  -  -               [17/Jan/2020:10:18:11 +0000] "GET /category/finance HTTP/1.1" 200      83                "/category/books?from=20" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" 5175 1477 8842`

**Comment by martin-helmich** [comment]
This is odd. I have been able to reproduce this issue, although the configured log format seems correct. I will investigate some more. Thanks for the report! :+1:

**Comment by martin-helmich** [comment]
Scratch that; I've just added a test case for this issue in commit 6961618 which passes successfully (when I thought I had reproduced this issue earlier, it was with a wrong config 🤦‍♂).

How exactly does the exporter "fail" to parse this log file? Are there any error messages? Do you see one the `<namespace>_parse_errors_total` metric increasing?

**Comment by martin-helmich** [comment]
I'd also like to note that the exporter opens the access log file at **the end of the file**, so that it will only scrape access log entries that are written **after** the exporter has been started (see #54 for the reasoning behind this). Maybe that's the case, here?
