### ISSUE TITLE
there is no ./prometheus-nginxlog-exporter executable

### ISSUE THREAD

**Issue by chrisquin** [martin-helmich/prometheus-nginxlog-exporter#95]
not clear what to do ...

I cloned the current master and in the **Readme** there is the usage section:

> Use the command-line:

```
./prometheus-nginxlog-exporter \
  -format="<FORMAT>" \
  -listen-port=4040 \
  -namespace=nginx \
  [PATHS-TO-LOGFILES...]
```

But i can't find no executable `prometheus-nginxlog-exporter`. Do i have to build it from go files? (I am not familiar with go)

**Comment by frenkye** [comment]
Dont clone go to release page https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases

**Comment by martin-helmich** [comment]
I can only reiterate on the previous comment; if you simply want to _use_ the exporter, you're best off with the [pre-built binary](https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases) (only Linux/amd64, currently). If you want to build it yourself (for development, or for other platforms), run either `go get github.com/martin-helmich/prometheus-nginxlog-exporter` or clone this repository and run `go build` in the project root.
